### ISSUE TITLE
Ability to determine public keys that a message has been encrypted for (i.e. recipients)?

### ISSUE THREAD

**Issue by ghost** [krzyzanowskim/ObjectivePGP#10]
Is it possible to add an API call which allows one to determine the public keys that a message has been encrypted for - i.e. its recipients? I am thinking along the lines of what one can do with the GPG cli:

`cat message.pgp | LANG=C gpg --verbose --list-only 2>&1 | grep 'gpg: public key is'` 

(see: http://security.stackexchange.com/questions/82674/ability-to-determine-which-pgp-public-keys-a-message-has-been-encrypted-for/82678#82678)

That way, the program can determine the correct private key to try to decrypt the message. Or alternately if you are editing an encrypted file, you can automatically re-save it with the same recipients as before.

**Comment by dstan2** [comment]
I just figured out how to do this with the existing library. 
The crux of it is to convert the message to data with PGPArmor, give the data to PGPPacketFactory, and to get the keyID from the PGPPublicKeyEncryptedSessionKeyPacket. This information was really helpful in figuring out what to do: https://tools.ietf.org/html/rfc4880#section-5.1

This is the function I wrote that returns an array of recipient keys, though it will only include a key if it is loaded in your instance of ObjectivePGP


 -(NSArray *) getRecipientKeysForPGPMessage:(NSString *) message {
    NSError *error = nil;
    NSData *messageData = [PGPArmor readArmoredData:message error:&error];
    
    if (messageData && !error) {
        NSMutableArray *recipientKeyArray = [[NSMutableArray alloc] init];
        NSUInteger offset = 0;
        PGPPacket *packet = [PGPPacketFactory packetWithData:messageData offset:offset];
        
        while ([packet isKindOfClass:[PGPPublicKeyEncryptedSessionKeyPacket class]]) {
            PGPKeyID *id = ((PGPPublicKeyEncryptedSessionKeyPacket *)packet).keyID;
            PGPKey *recipientKey = [self.pgp getKeyForKeyID:id type:PGPKeySecret];
            if (recipientKey) {
                [recipientKeyArray addObject: recipientKey];
            }
            offset += [packet.headerData length];
            offset += [packet.bodyData length];
            packet = [PGPPacketFactory packetWithData:messageData offset:offset];
        }
        return recipientKeyArray;
        
    } else {
        NSLog(@"Error converting message into data");
        return NULL;
    }
}

**Comment by krzyzanowskim** [comment]
Available in https://github.com/krzyzanowskim/ObjectivePGP/releases/tag/0.10.0-beta1
