### ISSUE TITLE
Installation: Shell script invocation error

### ISSUE THREAD

**Issue by rodrigobdz** [krzyzanowskim/ObjectivePGP#100]
The [README](https://github.com/krzyzanowskim/ObjectivePGP/tree/ab29f338a010d5de1f8cc51c697332167d7b4891) lacks one step from [Apple's documentation to embedding a framework](https://developer.apple.com/library/content/technotes/tn2435/_index.html). Without this step, an error is produced when following the [current installation instructions](https://github.com/krzyzanowskim/ObjectivePGP/tree/ab29f338a010d5de1f8cc51c697332167d7b4891#objectivepgpframework).

The missing step in the README is:
> Add a **New Copy Files Phase** by selecting the Add icon, highlighted in Figure 4. Set the Destination field to Frameworks, and add the framework to the list. Ensure Code Sign on Copy is checked.

Figure 4 from Apple's documentation
![image](https://user-images.githubusercontent.com/14152377/35073501-5b50bc50-fbe9-11e7-8d8a-3c8ce47c8e44.png)
### Details

- ObjectivePGP version 0.9.5
- Error log
`bash: /Users/rodrigo/Library/Developer/Xcode/DerivedData/pgpPlayground-blwmqrymcaklsofdsusvxwapszrb/Build/Products/Debug-iphonesimulator/pgpPlayground.app/Frameworks/ObjectivePGP.framework/strip-frameworks.sh: No such file or directory`

**Comment by krzyzanowskim** [comment]
Thanks. updated!
