### ISSUE TITLE
Encrypting large amounts of data uses too much memory

### ISSUE THREAD

**Issue by daniel-legler** [krzyzanowskim/ObjectivePGP#102]
When encrypting large files (50-100 MB) on an iOS device using ObjectivePGP the memory usage gets so high that iOS shuts down the app. I've seen memory consumption increase by over 1 GB when encrypting a 100MB file. I've made a basic [project with a unit test](https://github.com/daniel-legler/opgp_large_file_test) in it that demonstrates the spike in memory use. This is all seen with default settings of ObjectivePGP v0.9.5.

Is this expected, or is there any way I can improve this behavior? If not, it would be great if you could dig in to this a bit and see if there are any options for improving performance.

**Comment by krzyzanowskim** [comment]
Thanks for the report. I'm aware of some problems with a large amount of data, though I guess the quickest fix will be autorelease pool somewhere, the footprint shouldn't be that big.

**Comment by krzyzanowskim** [comment]
Hm... from the quick checks, the footprint is at a reasonable level when running Objective-C code, but not necessarily when running Swift. If you have a chance, can you repeat the tests with ObjC only?

**Comment by krzyzanowskim** [comment]
The quick changes reduced the reported overhead by 2. Not great yet, but 2x better ;)

**Comment by daniel-legler** [comment]
@krzyzanowskim I rewrote the test to Objective-C and unfortunately I'm seeing the same results with this version of my unit test.

**Comment by krzyzanowskim** [comment]
@daniel-legler yes, but you should notice the improvement fetching the current `develop` branch.

**Comment by daniel-legler** [comment]
@krzyzanowskim Yep! With the newest commits memory use peaked at only about 5x the file size whereas before it was around 10x. That is a huge improvement, thank you for the quick fixes!

**Comment by krzyzanowskim** [comment]
I'm closing this one as the fix is not easy to make right now, but I'll schedule it for the future. The quick fix should be enough. The expected memory peak is ~3x of the encrypted file.

**Comment by daniel-legler** [comment]
@krzyzanowskim Any updates on this issue?

I've also just recently run into another memory problem in ObjectivePGP. When reading keys from a file with several hundred keys in it, the framework again causes a crash on a device because it consumes so much memory. This seems weird to me since the keyring is still less than 1MB in size, and I'm going to try to write a unit test to show this but if you can also look into this problem that would be great.

**Comment by krzyzanowskim** [comment]
Thanks, looks like adding @autorelease somwhere should help with that
