### ISSUE TITLE
Decrypting with password

### ISSUE THREAD

**Issue by john7770** [krzyzanowskim/ObjectivePGP#103]
I updated the framework in my code to new one since 2/2/18

I can't seem to figure out how to decrypt data with a key that has a passphrase in swift as I did before. I keep getting an error I don't understand here it is: 
<img width="1229" alt="screen shot 2018-02-02 at 5 45 29 pm cst" src="https://user-images.githubusercontent.com/19157445/35759777-7e59cc78-0841-11e8-82e6-06bdbd380736.png">
the text reads:
`let decryptedData: Data = try ObjectivePGP.decrypt(encryptedM, andVerifySignature: true, using: keys, passphraseForKey: self.keyPass as String?);`
error: Cannot convert value of type 'String?' to expected argument type '((Key?) -> String?)?'
where keyPass is a user entered string

I've tried many ties but I can't seem to find a way to make it work

**Comment by krzyzanowskim** [comment]
This is a closure, inside you return the password for the key.
