### ISSUE TITLE
PGPUserIDPacket - use of unresolved identifier

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#104]
Until 0.8.0 i used
`let user = PGPUser(userIDPacket: PGPUserIDPacket(userID: userID))`
to create an user from its user ID

Beginning of 0.9.0 when calling
`let user = User(userIDPacket: PGPUserIDPacket(userID: userID))`
`PGPUserIDPacket` is unresolved

**Comment by krzyzanowskim** [comment]
It's private now (PGPUser initializer is private too). What is the use case that you need it?

**Comment by tobiasjungnickel** [comment]
i used it to create a pseudo user (without key) from an userID. Could have worked around really easy.
