### ISSUE TITLE
Can't encrypt using DSA keys generated via GPGSuite

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#105]
Steps to repro:
1. Generate new 3072 length key via GPGSuite with DSA/Elgamal
2. Import key into ObjectivePGP
3. Try and encrypt data using the key

Returns:
```
Error Domain=com.objectivepgp Code=-1 "Cannot encrypt. Missing required MPI. Invalid key." UserInfo={NSLocalizedDescription=Cannot encrypt. Missing required MPI. Invalid key.}
```

**Comment by krzyzanowskim** [comment]
![screen shot 2018-02-08 at 11 35 51](https://user-images.githubusercontent.com/758033/35968467-3db07758-0cc4-11e8-9a77-302a722d83ed.png)

**Comment by dsanghan** [comment]
@krzyzanowskim: 👍
