### ISSUE TITLE
DSA Sign only key memory corruption

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#106]
Steps to repro:
1. Generate a new sign-only key via GPGSuite with DSA (3072)
2. Import into ObjectivePGP
3. Try to sign data using that key.

EXC_BAD_ACCESS on `PGPDsa.m`:
```
DSA_SIG * _Nullable sig = DSA_do_sign(toSign.bytes, (int)toSign.length, dsa);
```

I verified that `toSign` isn't nil.

**Comment by dsanghan** [comment]
Is this also something that isn't supported?

**Comment by krzyzanowskim** [comment]
;-) unlikely. I'll take a look a it.

**Comment by krzyzanowskim** [comment]
can't reproduce. Can you attach the keys and message that cause the problems to verify?

**Comment by krzyzanowskim** [comment]
I see now, it happens with the key with a password.

**Comment by krzyzanowskim** [comment]
Fixed.
