### ISSUE TITLE
ECDSA Packet Parsing Issue

### ISSUE THREAD

**Issue by benjbellon** [krzyzanowskim/ObjectivePGP#108]
https://github.com/krzyzanowskim/ObjectivePGP/blob/3ac2b25d279fb93b93c02907ff51cd49a071cea0/ObjectivePGP/Packets/PGPPublicKeyPacket.m#L139

When attempting to parse ECDSA packets, it appears an error is thrown, causing `nil` to be returned. This causes `readKeysFromData` to fail, and the packet remains unparsed. I'm happy to look into this if I have some time, unless you happen to know of any limitations in the current implementation before I read the [RFC 4880 Spec](https://tools.ietf.org/html/rfc4880)

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/ObjectivePGP/issues/92
it's not in the 4880 though.

**Comment by benjbellon** [comment]
@krzyzanowskim That refers to tag 22. I believe my issue is related to Tag 19.

**Comment by krzyzanowskim** [comment]
The same. Elliptic Curves are not supported.

**Comment by benjbellon** [comment]
@krzyzanowskim  Ah fantastic. Thanks for the info! Do you mind if I take a crack at it? Or is something already in the works?

**Comment by benjbellon** [comment]
Thanks. I'll push an implementation if
