### ISSUE TITLE
CocoaPods (easy way) Problem

### ISSUE THREAD

**Issue by dushmantha** [krzyzanowskim/ObjectivePGP#11]
Unable to use following command in terminal please help me "pod 'ObjectivePGP', :git => 'https://github.com/krzyzanowskim/ObjectivePGP.git', :branch => :master "

Error:-bash: https://github.com/krzyzanowskim/ObjectivePGP.git,: No such file or directory
my pod version is :0.35.0

**Comment by krzyzanowskim** [comment]
this phrase should be placed in your Podfile file

**Comment by dushmantha** [comment]
Thanks for you reply. I clone project from github. but when I run this method [pgp importKeysFromFile:@"/path/to/secring.gpg" allowDuplicates:NO]; in my project return array is null.

**Comment by krzyzanowskim** [comment]
you shoud replace "/path/to/myfile.gpg" with path to the keyring file, accessible by your application.

**Comment by dushmantha** [comment]
thanks you... I added to key file path from NSString *filePath = [[NSBundle mainBundle] pathForResource:@"mykey_pub" ofType:@"gpg"] now its working.. thanks
