### ISSUE TITLE
Encript string using Public key

### ISSUE THREAD

**Issue by GefMar** [krzyzanowskim/ObjectivePGP#111]
i'm read public key, 

`let parse_key = ObjectivePGP.readKeys(from: pub_key!.data(using: .utf8, allowLossyConversion: false)!)`

its good, result from debug: [<PGPKey: 0x60000002e460>, publicKey: 5A49DD16F1970AC2, secretKey: (null)]

i use this key, 
`let enc_message = try ObjectivePGP.encrypt(str.data(using: .utf8)!, using: key, armored: false)`

error: Error Domain=com.objectivepgp Code=0 "Encryption key not found" UserInfo={NSLocalizedDescription=Encryption key not found}

what am I doing wrong?

**Comment by GefMar** [comment]
UDP:
key string
`"-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: BCPG v@RELEASE_NAME@\n\nmQENBFrgQNMDCACoFOO2fN3SKaELPGGZz6P+5WXCBKscB/YAv5r3PnbYi6ShWw8M\npCEeUkXktbxY5907UFrF7z6kBsG3QCTZOn53TPJrQ9zyyLLv+jdJymKFUwQJhV33\nJWKcb4yxawLMVJYPMpc3t3DiAx11+Hcy/IrTGPHoxDBhZWp+VOByLqa6DcgInjty\naUg7tt9PfYkG25DAYowcBTJGOXi2YssSQ3e1h8gfXucc24zZfwXZ03daazXA6hmA\nROQiS6d5O8IPPxN7fpI2sYbVOOq07RFNwzO1u9f6cMUk+0U85f8EMqp9omRsmf33\nB1aQsC4pbC4MpAQS4YXmiUeDhSj7BbcI+XHPABEBAAG0E2phbi5yYWJlQGtpYm90\ndS5uZXSJAS4EEwMCABgFAlrgQNQCG4MECwkIBwYVCAIJCgsCHgEACgkQmT9b0M9Y\nbGzeEwgAhl44AtS4kilRUtKcnPirw44mr2VHm/omk5H6uVW2LdvgqHIvNFT48BbV\n96/vzSlcbcf7ckA5PCnQfnYGZwrmIEwvzz3D9R04J7G59i9QwsS86lMh53xHj7X6\n9C0wN2EGhxfbStmbwPxQM7ZDVh//etCgXZw2by/IlEy73Qxv2dgmx4VNqMFkQxo+\nviq5ucxcnhipg55asMmyMPavYIyReW7AKJMTvmGph4xfAEZGVrn4fkOm8kbG+Hc7\nztxgj66Ewxok1lUMjYvwC+ZK27RxCVomD5MRBlJbBAFZCqC4ccCJATUTLOK/zdMl\ns7IqLTLl+ry50vV5sBA6ibSZdMfEz7kBDQRa4EDUAggAoyP4CE3Xg3ImZpND/amf\nJPrOdPj02k2GzM786BiPO4hq7qC216VsF0OAGh5CZJiyeshokcruxBWWvSTa5x8U\nfrUeHIkiq9fTwD90m4P0+jhmo63kvwdiZ40lPQS5DUAFXH1FOHsE22XgT8mlcpqt\ncDECjH8npnUoCPODGVaKyE6YNY+2+rLOxF3OjtV7T+sWbRZ3TLAD1SrvMQAiTnoQ\nDHlZtHhToqAjBpbihPTKR/jnsTUrM3Um5YNhJkSEpQH8Lxh4eN/wGFFMUizcULyp\nV71PjQyKRvDxM2SnuWxS7nI4a5kZBLsZHtPBcNjqHWI41/A9B6xOmgDEpLrsYBu/\n4wARAQABiQEfBBgDAgAJBQJa4EDUAhsMAAoJEJk/W9DPWGxsT2oH/jaCy72LeAfA\nLgYD4AHW9JgUBkhq4CMKxKDlCd4kDZpY5j33szPbwIR1QMW7a9fqQGcnz/O3nQRT\nS6uUYFM8q0nPglIdsMmsSKOJOyPBZsTQQAkVdp9lYFBPA/EKyEIuAZPnNV+UK7mj\nufpkIpGvbnkz4CLke/U5hGaKIPg4OtRjkM0KDk1v8mJOAC/2eIeJbU9ze/hIxULw\nZAbEWfgXHl68YIRTWrPZo4O/jAvZ/KNsPmRieXod81lqXKo/He+nrF1bzzWXbiR6\nZLZDe2lhA6m4Puo8ng41ZjaUReyfj/r0mVMnA9qI59trY0vNucKpZdHhMjqKVSvW\nlJb9nBr5v70=\n=hZ8O\n-----END PGP PUBLIC KEY BLOCK-----\n"`

i read key 
`let k_p = try ObjectivePGP.readKeys(from: arm_key.data(using: .utf8)!)`

this key not encrypt data in ObjectivePGP, This key works in another library in Kotlin

**Comment by krzyzanowskim** [comment]
can you please create gist with exact code you're using, so I can copy&paste it to verify on my side?

**Comment by GefMar** [comment]
`let keyStr = "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: BCPG v@RELEASE_NAME@\n\nmQENBFrgQNMDCACoFOO2fN3SKaELPGGZz6P+5WXCBKscB/YAv5r3PnbYi6ShWw8M\npCEeUkXktbxY5907UFrF7z6kBsG3QCTZOn53TPJrQ9zyyLLv+jdJymKFUwQJhV33\nJWKcb4yxawLMVJYPMpc3t3DiAx11+Hcy/IrTGPHoxDBhZWp+VOByLqa6DcgInjty\naUg7tt9PfYkG25DAYowcBTJGOXi2YssSQ3e1h8gfXucc24zZfwXZ03daazXA6hmA\nROQiS6d5O8IPPxN7fpI2sYbVOOq07RFNwzO1u9f6cMUk+0U85f8EMqp9omRsmf33\nB1aQsC4pbC4MpAQS4YXmiUeDhSj7BbcI+XHPABEBAAG0E2phbi5yYWJlQGtpYm90\ndS5uZXSJAS4EEwMCABgFAlrgQNQCG4MECwkIBwYVCAIJCgsCHgEACgkQmT9b0M9Y\nbGzeEwgAhl44AtS4kilRUtKcnPirw44mr2VHm/omk5H6uVW2LdvgqHIvNFT48BbV\n96/vzSlcbcf7ckA5PCnQfnYGZwrmIEwvzz3D9R04J7G59i9QwsS86lMh53xHj7X6\n9C0wN2EGhxfbStmbwPxQM7ZDVh//etCgXZw2by/IlEy73Qxv2dgmx4VNqMFkQxo+\nviq5ucxcnhipg55asMmyMPavYIyReW7AKJMTvmGph4xfAEZGVrn4fkOm8kbG+Hc7\nztxgj66Ewxok1lUMjYvwC+ZK27RxCVomD5MRBlJbBAFZCqC4ccCJATUTLOK/zdMl\ns7IqLTLl+ry50vV5sBA6ibSZdMfEz7kBDQRa4EDUAggAoyP4CE3Xg3ImZpND/amf\nJPrOdPj02k2GzM786BiPO4hq7qC216VsF0OAGh5CZJiyeshokcruxBWWvSTa5x8U\nfrUeHIkiq9fTwD90m4P0+jhmo63kvwdiZ40lPQS5DUAFXH1FOHsE22XgT8mlcpqt\ncDECjH8npnUoCPODGVaKyE6YNY+2+rLOxF3OjtV7T+sWbRZ3TLAD1SrvMQAiTnoQ\nDHlZtHhToqAjBpbihPTKR/jnsTUrM3Um5YNhJkSEpQH8Lxh4eN/wGFFMUizcULyp\nV71PjQyKRvDxM2SnuWxS7nI4a5kZBLsZHtPBcNjqHWI41/A9B6xOmgDEpLrsYBu/\n4wARAQABiQEfBBgDAgAJBQJa4EDUAhsMAAoJEJk/W9DPWGxsT2oH/jaCy72LeAfA\nLgYD4AHW9JgUBkhq4CMKxKDlCd4kDZpY5j33szPbwIR1QMW7a9fqQGcnz/O3nQRT\nS6uUYFM8q0nPglIdsMmsSKOJOyPBZsTQQAkVdp9lYFBPA/EKyEIuAZPnNV+UK7mj\nufpkIpGvbnkz4CLke/U5hGaKIPg4OtRjkM0KDk1v8mJOAC/2eIeJbU9ze/hIxULw\nZAbEWfgXHl68YIRTWrPZo4O/jAvZ/KNsPmRieXod81lqXKo/He+nrF1bzzWXbiR6\nZLZDe2lhA6m4Puo8ng41ZjaUReyfj/r0mVMnA9qI59trY0vNucKpZdHhMjqKVSvW\nlJb9nBr5v70=\n=hZ8O\n-----END PGP PUBLIC KEY BLOCK-----\n"
        do {
            
            let rKey = try ObjectivePGP.readKeys(from: keyStr.data(using: .utf8)!)
            let encMessage = try ObjectivePGP.encrypt(keyStr.data(using: .utf8)!, addSignature: false, using: rKey)
            
            let res_message = Armor.armored(encMessage, as: .message)
            print(res_message)
            
        }catch{
            print(error)
        }`

**Comment by GefMar** [comment]
AND 
`let keyStr = "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: BCPG v@RELEASE_NAME@\n\nmQENBFrgQNMDCACoFOO2fN3SKaELPGGZz6P+5WXCBKscB/YAv5r3PnbYi6ShWw8M\npCEeUkXktbxY5907UFrF7z6kBsG3QCTZOn53TPJrQ9zyyLLv+jdJymKFUwQJhV33\nJWKcb4yxawLMVJYPMpc3t3DiAx11+Hcy/IrTGPHoxDBhZWp+VOByLqa6DcgInjty\naUg7tt9PfYkG25DAYowcBTJGOXi2YssSQ3e1h8gfXucc24zZfwXZ03daazXA6hmA\nROQiS6d5O8IPPxN7fpI2sYbVOOq07RFNwzO1u9f6cMUk+0U85f8EMqp9omRsmf33\nB1aQsC4pbC4MpAQS4YXmiUeDhSj7BbcI+XHPABEBAAG0E2phbi5yYWJlQGtpYm90\ndS5uZXSJAS4EEwMCABgFAlrgQNQCG4MECwkIBwYVCAIJCgsCHgEACgkQmT9b0M9Y\nbGzeEwgAhl44AtS4kilRUtKcnPirw44mr2VHm/omk5H6uVW2LdvgqHIvNFT48BbV\n96/vzSlcbcf7ckA5PCnQfnYGZwrmIEwvzz3D9R04J7G59i9QwsS86lMh53xHj7X6\n9C0wN2EGhxfbStmbwPxQM7ZDVh//etCgXZw2by/IlEy73Qxv2dgmx4VNqMFkQxo+\nviq5ucxcnhipg55asMmyMPavYIyReW7AKJMTvmGph4xfAEZGVrn4fkOm8kbG+Hc7\nztxgj66Ewxok1lUMjYvwC+ZK27RxCVomD5MRBlJbBAFZCqC4ccCJATUTLOK/zdMl\ns7IqLTLl+ry50vV5sBA6ibSZdMfEz7kBDQRa4EDUAggAoyP4CE3Xg3ImZpND/amf\nJPrOdPj02k2GzM786BiPO4hq7qC216VsF0OAGh5CZJiyeshokcruxBWWvSTa5x8U\nfrUeHIkiq9fTwD90m4P0+jhmo63kvwdiZ40lPQS5DUAFXH1FOHsE22XgT8mlcpqt\ncDECjH8npnUoCPODGVaKyE6YNY+2+rLOxF3OjtV7T+sWbRZ3TLAD1SrvMQAiTnoQ\nDHlZtHhToqAjBpbihPTKR/jnsTUrM3Um5YNhJkSEpQH8Lxh4eN/wGFFMUizcULyp\nV71PjQyKRvDxM2SnuWxS7nI4a5kZBLsZHtPBcNjqHWI41/A9B6xOmgDEpLrsYBu/\n4wARAQABiQEfBBgDAgAJBQJa4EDUAhsMAAoJEJk/W9DPWGxsT2oH/jaCy72LeAfA\nLgYD4AHW9JgUBkhq4CMKxKDlCd4kDZpY5j33szPbwIR1QMW7a9fqQGcnz/O3nQRT\nS6uUYFM8q0nPglIdsMmsSKOJOyPBZsTQQAkVdp9lYFBPA/EKyEIuAZPnNV+UK7mj\nufpkIpGvbnkz4CLke/U5hGaKIPg4OtRjkM0KDk1v8mJOAC/2eIeJbU9ze/hIxULw\nZAbEWfgXHl68YIRTWrPZo4O/jAvZ/KNsPmRieXod81lqXKo/He+nrF1bzzWXbiR6\nZLZDe2lhA6m4Puo8ng41ZjaUReyfj/r0mVMnA9qI59trY0vNucKpZdHhMjqKVSvW\nlJb9nBr5v70=\n=hZ8O\n-----END PGP PUBLIC KEY BLOCK-----\n"
        do {
            
//            let rKey = try ObjectivePGP.readKeys(from: keyStr.data(using: .utf8)!)
            let rKey = try Armor.readArmored(keyStr)
            let tKey = try ObjectivePGP.readKeys(from: rKey)
            let encMessage = try ObjectivePGP.encrypt(keyStr.data(using: .utf8)!, addSignature: false, using: tKey)
            
            let res_message = Armor.armored(encMessage, as: .message)
            print(res_message)
            
        }catch{
            print(error)
        }
        `

**Comment by krzyzanowskim** [comment]
https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by GefMar** [comment]
sorry. Update comment

**Comment by GefMar** [comment]
I was able to import the key into the utility GPGTools and it works.
The library imports it, but refuses to encrypt the data.

**Comment by GefMar** [comment]
The problem was resolved on its own, the problem was in the Androyd Library

**Comment by Maheepk** [comment]
@krzyzanowskim thanks for quick reply, 
What i Think? 
- I am thinking, I will get public key from Server Side, from that i will generate PGP Encrypted Message, which i am getting from above code, but if i put that Encrypted message to decrypt that its not working, I generated Public key from igolder.com and i am putting Enctypted message to test if it follow standard PGP Encryption. 

Q: How i will make sure my Encrypted message is Follow Standards?

**Comment by krzyzanowskim** [comment]
A: don't use random site that you'll find via google is a good start. Try GPG
