### ISSUE TITLE
Can't encrypt with public key

### ISSUE THREAD

**Issue by kiritoxcii** [krzyzanowskim/ObjectivePGP#115]
- ObjectivePGP version: 0.12.1
- Platform (iOS/macOS):  iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name:

It happens with the 0.12 framework too, adding it manually

# Description
I'm using this public key to encrypt a string, but the library does not encrypt

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.43

mQENBFsam68BCADe8xI3XltPB7xjIj5zYb6h2K4t65ycXFjLH+58iqRXGklbyrmG
zGjZ/jfJ3Y0JTKqOjnEVaArnZ7YgAu2xTwJpzZ83zuqsVbahtwYvYgxszYSIGFkK
G5qF07erDmfI3H4TuHWCcBlZdh48j5dPIzCzjU5IYitSEWglgZzqXnDXRf5HNiiD
Ea8Q2EFwQznwJxpfUshsoLunQmb/r1RruRJbBpfzkGKQq0+Y1Djo2LB1y2FFWCC6
bLA2uVSdybfPYOBUuiSbSnLUJPGRllD15WDVny1QNttg98sxpgrMYYwUlIHodogN
cSuH5z5+Potmnt1hBSEwvYpc0D5ujiBQKyuXABEBAAG0CkNpbmVtYXJrODCJARwE
EAECAAYFAlsam68ACgkQ8vnhDYIE6+hNEQf+PEZ7JtyCa0vrSREWbMc+GQCXZXYJ
oyWtLPJTqZ55lRi9Bku4UMda89KtQ7ud3VnTCu2CvWPwtxB1s++/jVYiDc8fwWNp
h84jxBt18BrhAj82xT1vtrZQ2rHsa6873qDH6sNY5Iy4WdSXS0QftbDtaDWxu5lD
6NM0v/NQDkWrjrC0ZRSiRfjWRBz986woZRjAB7eh/7SvBntJf67cZilD0FvL8gnF
gbZnov6uvXSOhQTTOCjnvDCw0+zBeCeXWIN6uhlU/QKjFZKjt72Pw+rDKyeHwJsD
Etl9Mx20/3QvwB+oeAeo3KXKmNL2ki8m7BkJutkxuli5Cq+b5b7ZL3susQ==
=1H1I
-----END PGP PUBLIC KEY BLOCK-----

# Steps to reproduce

Sample code to reproduce the issue:

```objective-c

NSString * string = @"205";
 NSData * stringData = [string dataUsingEncoding:NSUTF8StringEncoding];
    NSString * publicKeyPath = [[NSBundle mainBundle] pathForResource: @"test_public_key"  ofType:@"asc"];

    NSError *error;
    NSArray<PGPKey *> *pgpKeys = [ObjectivePGP readKeysFromPath:publicKeyPath error:&error];
    
    NSData * encryptedStringData = [ObjectivePGP encrypt:stringData addSignature:NO usingKeys:pgpKeys passphraseForKey:nil error:&error];

    NSString * armoredString = [PGPArmor armored:encryptedStringData as:PGPArmorMessage];
```
"armoredString" values is:

-----BEGIN PGP MESSAGE-----
Version: ObjectivePGP
Comment: https://www.objectivepgp.com
Charset: UTF-8

0jcBn2HpPYasasGbWk7DbkiWWPYKc8M1EUppNptLr7ubL/wIJyO0iOf2Iw7mp9QLVUAtK5Hq6gvL
=QAEe
-----END PGP MESSAGE-----

But that's not a real encryption, I've used this public key in online encrypt/decrypt tools and it works, the public key is generated by another platform, and I do not have access to the way they generate the key

**Comment by Maheepk** [comment]
@kiritoxcii did you find solution of above problem?

**Comment by orazz** [comment]
any solution for this?

**Comment by krzyzanowskim** [comment]
This problem was addressed by https://github.com/krzyzanowskim/ObjectivePGP/commit/ba53d32da75a6bb357d679c55f133e652713347b
<img width="886" alt="Screenshot 2021-07-14 at 18 39 36" src="https://user-images.githubusercontent.com/758033/125659832-6ccdeb1c-284c-4a57-9d02-0f0c299b6250.png">
