### ISSUE TITLE
Signing doesn't seem to work

### ISSUE THREAD

**Issue by Rivukis** [krzyzanowskim/ObjectivePGP#117]
- ObjectivePGP version: 0.12.1
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name: What project?

# Description

I've tried to use signatures and I can't get it to work. If I specify to verify signature it always works even when encrypting it with add signature set to false. If I use verifySignature directly then it always throws 'nilError'. I also can't find a single example that uses signatures. Looked in tests and example playground.

# Steps to reproduce

Write in Swift. Use Armor. Try all combinations of keys (public only, private only, private and public combined, combine sender and receiver keys, etc.), and encryption, decryption, verifySignature, etc.

**Comment by Rivukis** [comment]
Also, I'm trying to sign encrypted data, not plain text

**Comment by krzyzanowskim** [comment]
There is an example for sign&verify in README https://github.com/krzyzanowskim/ObjectivePGP#sign--verify-data-or-file

I'm not aware of an example where it doesn't work. If you have any, I'd need the code + keys u use to reproduce it locally.
