### ISSUE TITLE
expirationDate for expired key is nil

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#120]
- ObjectivePGP version: 0.12.2
- Platform (iOS/macOS): iOS 12
- Installation method (CocoaPods/Carthage/...): CocoaPods

# Description
When reading an expired key the expirationDate is nil. It seems like you can distinguish an expired key with a workaround that it has no primaryUser to a key that never expires. But my suggestion is that expirationDate should always return the date for keys that expire or are expired.

# Steps to reproduce

Choose a (public) key that has an expiration date and already expired.

Sample code to reproduce the issue:

```swift

let key = try ObjectivePGP.readKeys(fromPath: url.path).first!
if let expirationDate = key.expirationDate {
    return true
}

```

**Comment by krzyzanowskim** [comment]
> It seems like you can distinguish an expired key with a workaround that it has no primaryUser to a key that never expires.

hm... this shouldn't depends on expiration status.

**Comment by tobiasjungnickel** [comment]
fixed 👍
