### ISSUE TITLE
Issue Generating Framework w/ Bitcode Enabled

### ISSUE THREAD

**Issue by bnotions-fahad** [krzyzanowskim/ObjectivePGP#121]
- ObjectivePGP version: 0.12.3
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): Generating framework w/ provided script
- Project name: N/A

# Description
Attempting to generate the framework with Bitcode enabled

# Steps to reproduce
1. Set bitcode enabled to true
2. Generate iphone os framework via script
3. Move generated framework into project
4. Attempt to archive project
Receive the following error:
```
14:08:40 Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in ObjectivePGP.framework/ObjectivePGP:
14:08:40 error: Cannot extract bundle from /var/folders/dc/dtmsswnn4231ybn45dzhcdjc0000gp/T/XcodeDistPipeline.yOB/Root/Payload/TestApp.app/Frameworks/ObjectivePGP.framework/ObjectivePGP (i386)
```

**Comment by krzyzanowskim** [comment]
It's not gonna work https://github.com/krzyzanowskim/ObjectivePGP/issues/73#issuecomment-331821302

**Comment by tobiasjungnickel** [comment]
can you please check if enabling bitcode is possible now

**Comment by krzyzanowskim** [comment]
it's not afaik

**Comment by HowardCsie** [comment]
I need bitcode support.
