### ISSUE TITLE
Importing existing keys

### ISSUE THREAD

**Issue by adur1990** [krzyzanowskim/ObjectivePGP#123]
- ObjectivePGP version: 0.13.0
- Platform (iOS/macOS): macOS
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name: Passafari

# Description
Is there a way to import a public/private keypair besides ASCII armored? I am developing a macOS app, which needs access to exactly one keypair and I think it would be annoying to ask the user if he could first export the key to ASCII armor, since the keypair is already present on disk.

Thank you for your help :)

**Comment by krzyzanowskim** [comment]
you don't need ASCII armored format for keys, you can just use binary format

**Comment by adur1990** [comment]
Okay, but how? Public keys are stored in `$HOME/.gnupg/pubring.gpg`, whereas private keys are in a seperate folder: `$HOME/.gnupg/private-keys-v1.d`. I do not und erstand how to read a keypair... Sorry for this noob question, but I'm really stuck.

**Comment by krzyzanowskim** [comment]
Use Keyring https://github.com/krzyzanowskim/ObjectivePGP#keyring and read one file after another. You'll end with a pairs of keys in a keyring

**Comment by adur1990** [comment]
Okay, after digging around in your code I think, that the keypair has to be exported using gpg-agent first, before it can be imported using ObjectivePGP. As far as I can see, there is no way to import the encrypted private key from the .gnupg/private-keys-v1.d folder. Would be a bummer...

**Comment by krzyzanowskim** [comment]
recent gnupg version uses [keybox](https://www.gnupg.org/faq/whats-new-in-2.1.html#keybox) format for public keys, and [gpg-agent manages secret keys](https://www.gnupg.org/faq/whats-new-in-2.1.html#nosecring) (in `private-keys-v1.d`) - that is not compatible with standard OpenPGP keyring format, and not supported by the ObjectivePGP.

The `gpg --export-secret-keys` still creates an OpenPGP compliant file with the secret keys
