### ISSUE TITLE
Bad computation of RSA iqmp parameter ("U")

### ISSUE THREAD

**Issue by daniele-athome** [krzyzanowskim/ObjectivePGP#129]
I believe computation of rsa->iqmp ("U" parameter) is not correct.

https://github.com/krzyzanowskim/ObjectivePGP/blob/0bbde2d23307c80f83de0615b407a745f5de93b5/ObjectivePGP/CryptoBox/PGPRSA.m#L248

P and Q should be inverted here, right?

References:
https://tools.ietf.org/html/rfc8017#appendix-C

```
       coefficient       INTEGER,  -- (inverse of q) mod p
```

https://github.com/openssl/openssl/blob/master/crypto/rsa/rsa_gen.c#L365
```
 /* calculate inverse of q mod p */
        if (!BN_mod_inverse(rsa->iqmp, rsa->q, p, ctx)) {
            BN_free(p);
            goto err;
}
```

I'm just using intuition here, I'm not a crypto expert. However there is also the fact that the U parameter makes the private key not usable in OpenSSL (re-calculating it by calling BN_mod_inverse in the right way fixes the problem).
What I can't explain is how can this produce correctly formed PGP keys (I haven't tried that yet, sorry, and maybe I'm completely mistaken about everything :D but I thought I should share this concern).

**Comment by krzyzanowskim** [comment]
It's fine because P and Q is inverted in OpenSSL

**Comment by daniele-athome** [comment]
Wait how do you mean they are inverted? That OpenSSL sets P to `rsa->q` and Q to `rsa->p`? Isn't that a bug?

**Comment by krzyzanowskim** [comment]
see https://github.com/krzyzanowskim/ObjectivePGP/blob/0bbde2d23307c80f83de0615b407a745f5de93b5/ObjectivePGP/CryptoBox/PGPRSA.m#L79

nonetherless:
> `BIGNUM *BN_mod_inverse(BIGNUM *r, BIGNUM *a, const BIGNUM *n, BN_CTX *ctx);`
> BN_mod_inverse() computes the inverse of `a` modulo `n`

`BN_mod_inverse(NULL, RSA_get0_p(rsa), RSA_get0_q(rsa)` is inverse of `p` mod `q` that is speccified in RFC4880:

> - MPI of u, the multiplicative inverse of p, mod q.

**Comment by daniele-athome** [comment]
Ok thank you. In the meantime I believe I found the culprit:

From https://tools.ietf.org/html/rfc8017
```
The definition of the CRT coefficients here and the formulas that
use them in the primitives in Section 5 generally follow Garner's
algorithm [GARNER] (see also Algorithm 14.71 in [HANDBOOK]).
However, for compatibility with the representations of RSA
private keys in PKCS #1 v2.0 and previous versions, the roles of
p and q are reversed compared to the rest of the primes.  Thus,
the first CRT coefficient, qInv, is defined as the inverse of q
mod p, rather than as the inverse of R_1 mod r_2, i.e., of
p mod q.
```

Ok so to other lucky people unlikely to bump into this issue: just recalculate U in the opposite way and you will be able to convert the key for OpenSSL purposes.

Thanks for the help @krzyzanowskim!
