### ISSUE TITLE
How to I Decrypt  mail which coming me as Encrypted

### ISSUE THREAD

**Issue by SPrabhudesai** [krzyzanowskim/ObjectivePGP#136]
- ObjectivePGP version: 
- Platform (iOS/macOS): 
- Installation method (CocoaPods/Carthage/...): 
- Project name:

# Description
Hi how to I Decrypt mail which coming me as Encrypted

# Steps to reproduce

Sample code to reproduce the issue:

```objective-c
let key1 = KeyGenerator().generate(for: "", passphrase: nil)
let key2 = KeyGenerator().generate(for: "", passphrase: nil)
let plaintext = msgPlainBody!.data(using: String.Encoding.utf8)
let encryptedBin = try! ObjectivePGP.encrypt(plaintext!, addSignature: false, using: [key1, key2])
let encrypted = Armor.armored(encryptedBin, as: .message)
print(encrypted)

let signatureBin = try! ObjectivePGP.sign(encryptedBin, detached: true, using: [key1])
let signature = Armor.armored(signatureBin, as: .signature)
print(signature)
try! ObjectivePGP.verify(encryptedBin, withSignature: signatureBin, using: [key1])
let decrypted = try! ObjectivePGP.decrypt(encryptedBin, andVerifySignature: false, using: [key1])
print("Decrypted : \((decrypted))")
let backToString = String(data: decrypted, encoding: String.Encoding.utf8)
print("Decrypted : \((backToString)  ?? "s")")
```

In plaintext I got mail which send from PGP description but I am not able to Decrypt please help me as soon as possible

**Comment by krzyzanowskim** [comment]
There Playground has a working example of encryption and decryption: [ObjectivePGP.playground](https://github.com/krzyzanowskim/ObjectivePGP/blob/master/ObjectivePGP.playground/Contents.swift). You can use it as an example.
