### ISSUE TITLE
Documentation issue: PGPKey vs NSData type

### ISSUE THREAD

**Issue by klische** [krzyzanowskim/ObjectivePGP#138]
- ObjectivePGP version: 0.14.0
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods

# Description
The Obj-C example in the readme specifies key:
```objc
NSData *encrypted = [ObjectivePGP encrypt:fileContent addSignature:YES usingKeys:@[key] passphraseForKey:nil error:nil];
```
But the Swift example specifies two keys:
```swift
let encrypted = try ObjectivePGP.encrypt(fileContent), addSignature: true, using: [key1, key2])
```
Where does the 2nd key come from?

If one were to use the following methods, they produce keys in NSData format, but I don't see a way to create PGPKey from NSData? How would that then be passed into the Encrypt/Decrypt function?
```swift
let publicKey = try key.export(keyType: .public)
let secretKey = try key.export(keyType: .secret)
```

**Comment by krzyzanowskim** [comment]
> Where does the 2nd key come from?

one or more keys is accepted since you can encrypt using multiple keys. Public keys.

>  but I don't see a way to create PGPKey from NSData?

Use either `ObjectivePGP.readKeys(from:)` or [Keyring](https://github.com/krzyzanowskim/ObjectivePGP#keyring) or directly

**Comment by klische** [comment]
Thank you for the clarification.
