### ISSUE TITLE
CleartextSignedMessage Armor not implemented 

### ISSUE THREAD

**Issue by MainasuK** [krzyzanowskim/ObjectivePGP#139]
- ObjectivePGP version: 0.14.0
- Platform (iOS/macOS): iOS

# Description
Use `OpenPGP.sign` method create sign only message. 
Then `Armor.armored(messageData, .cleartextSignedMessage)`
The output only contains "-----BEGIN PGP MESSAGE-----" part.

Expect:
```
-----BEGIN PGP SIGNED MESSAGE-----

// clear text here
-----BEGIN PGP SIGNATURE-----
// payload here
-----END PGP SIGNATURE-----
```

**Comment by krzyzanowskim** [comment]
Thanks. This limitation is already listed in README.
