### ISSUE TITLE
Can't encrypt file

### ISSUE THREAD

**Issue by electrolobzik** [krzyzanowskim/ObjectivePGP#14]
I am trying to encrypt 200kb file (jpg):

```swift

func encryptFile(filename: String) -> String {
        
        var error: NSError?
        
        let fileContent = NSData(contentsOfFile: filename)
        
        var encryptedData = opgp.encryptData(fileContent, usingPublicKey:currentKey, armored:true, error:&error)
        if encryptedData != nil {
            NSLog("file encryption success")
            encryptedData.writeToFile(filename + ".gpg", atomically: true)
        }
        
        if error == nil {
            return "OK"
        } else {
            return "error: \(error)"
        }
    }

```

As result I am getting error:

```
Optional(Error Domain=BZIP2 Code=0 "BZ2_bzCompress failed" UserInfo=0x7fe7fb100df0 {NSLocalizedDescription=BZ2_bzCompress failed})
```

When I try to encrypt simple short text it works fine.

How should I encrypt file with the library? Thank you.

**Comment by krzyzanowskim** [comment]
give me, please, exact size of the file so I can try to reproduce the issue.

**Comment by electrolobzik** [comment]
I have prepared small test app which reproduces the issue. https://github.com/electrolobzik/ObjectivePgpTest

**Comment by joshsmoore** [comment]
I just wanted to add that I can reproduce this problem by grabbing any photo in the simulator photo application.

**Comment by joshsmoore** [comment]
I am actually getting this whenever I try to encrypt anything that is not text based

**Comment by BrosToch** [comment]
I think it happens for larger image. I'm able to encrypt for file size below 5kb.

**Comment by krzyzanowskim** [comment]
Check if this https://github.com/krzyzanowskim/ObjectivePGP/pull/31 fixed the issue

**Comment by ghaarsma** [comment]
This is still a problem. Please reopen. The problem is in bzip2Compressed, any time the compressed output is more then 10000 bytes (size of the buffer), it fails. 

I am looking at http://www.biu.ac.il/os_site/documentation/bzip2/manual_3.html#SEC20 to see how to fix this. If I succeed, I will put together a pull request.

**Comment by ghaarsma** [comment]
Created Pull request: https://github.com/krzyzanowskim/ObjectivePGP/pull/33 to take care off this bug.
