### ISSUE TITLE
Possible error in NSData pgp_Checksum method

### ISSUE THREAD

**Issue by Andrey-C** [krzyzanowskim/ObjectivePGP#142]
`/**  
 *  Calculates a 16bit sum of a string by adding each character * codes modulus 65535  
 *  
 *  @return checksum  
 */  
- (UInt16)pgp_Checksum {  
    UInt32 s = 0;  
    const UInt8 *bytes = self.bytes;  
    for (NSUInteger i = 0; i < self.length; i++) {  
        s = (s + (UInt8)bytes[i]);  
    }  
    s = s % 65536;  
    return (UInt16)s;  
}`

Shouldn't ` s = s % 65536;` rather be 65535 as stated in the comment above?

**Comment by krzyzanowskim** [comment]
Looks like comment is not valid, should be 65536

rfc says:
> a two-octet checksum is appended, which is equal to the sum of the preceding session key octets, not including the algorithm identifier, modulo 65536

> a two-octet checksum of the plaintext of the algorithm-specific portion (sum of all octets, mod 65536)

hence 65536. However the's cast to UInt16 that effectively trims the result to 65535.
