### ISSUE TITLE
Can't encrypt text when PGPKey object includes only public key

### ISSUE THREAD

**Issue by talentdeveloper** [krzyzanowskim/ObjectivePGP#143]
- ObjectivePGP version: 0.14.0
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name:

# Description
Need to encrypt text message with receiver's Public Key and I don't know receiver's Secret Key.
Generated PGPKey object `key1` with only public key, but couldn't encrypt plain/text with some errors. 
It seems that my error is similar with Issue #97 
Hope to know how I can solve this problem.
Regards

**Comment by krzyzanowskim** [comment]
do you have steps to reproduce the issue by any chance?

**Comment by ozobken** [comment]
You can still encrypt, but you can't sign at the moment - as per Issue #97

**Comment by talentdeveloper** [comment]
Thanks for your quick reply @krzyzanowskim and @ozobken 
It was my mistake due to using invalid PGP public key.
One more question,
 Which one would be a receiver's key in the array `usingKeys: [key1, key2]`, if I need `addSignature: true`
`key1` or `key2` ?

**Comment by krzyzanowskim** [comment]
will use each listed key to sign
