### ISSUE TITLE
No primaryUser

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#145]
- ObjectivePGP version: 0.14.0
- Platform (iOS/macOS): iOS 12.3.1
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name:

# Description

primaryUser for public key return nil even if it has users

# Steps to reproduce

Sample code to reproduce the issue:

[René Jungnickel (3D7FB565) – Public.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/3271112/Rene.Jungnickel.3D7FB565.Public.asc.zip)

```objective-c

let key = key in try ObjectivePGP.readKeys(fromPath: ...)
key?.publicKey?.primaryUser //returns nil
key?.publicKey?.user //return array of users

```

**Comment by krzyzanowskim** [comment]
It has users, but does it has a primary user? I dont't see the flag set for any user in the file.

**Comment by tobiasjungnickel** [comment]
Sorry, i thought a primary user is mandatory and one of the users automatically.
Can you post the command to get details about user(flag)s?
