### ISSUE TITLE
Expiration date from ObjectivePGP differ to gpg command

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#146]
- ObjectivePGP version: 0.14.0
- Platform (iOS/macOS): iOS 12.3.1
- Installation method (CocoaPods/Carthage/...): CocoaPods

# Description

Expiration date from ObjectivePGP differ to `gpg --list-packets`

# Steps to reproduce

Sample code to reproduce the issue:

[ExpirationDate.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/3271920/ExpirationDate.asc.zip)

```objective-c

let keys = try ObjectivePGP.readKeys(fromPath: ...)
key.expirationDate //2018-01-13 instead of 2021-01-12

```

**Comment by krzyzanowskim** [comment]
I remember I fixed tha once https://github.com/krzyzanowskim/ObjectivePGP/issues/130

I guess there's no primary user, and different user is taken

**Comment by tobiasjungnickel** [comment]
Right, the key has no primary user. It has 2 user ids and 2 subkeys. Both subkeys expire on 2020-01-18. Can i check for other expiration dates to validate the result of `key.expirationDate`?

**Comment by krzyzanowskim** [comment]
There is primary user specified with ID: `Dominic Räber` and three certificates where the latest was issued at 2019-02-22 with information that the key expires at 2021-01-12. That mean there's an issue with retriving the right date.
