### ISSUE TITLE
Decryption Issue

### ISSUE THREAD

**Issue by wongmh** [krzyzanowskim/ObjectivePGP#15]
I am currently working with ObjectivePGP to decrypt a simple testing GPG encrypted file. The error result is prompted as following:

2015-03-31 10:13:46.270 opgp[2990:79775] Unsuported subpacket type 131
2015-03-31 10:13:46.270 opgp[2990:79775] Unsuported subpacket type 32
ERROR: Valid PublicKeyEncryptedSessionKeyPacket not found

FYI, At the encryption side, the command line is as follow:
gpg --cipher-algo AES256 --compress-algo zlib --batch --passphrase="$Password" -c "$File"

Please advise. 
Thank you.

**Comment by krzyzanowskim** [comment]
It seems to be fixed with latest changes. Feel free to reopen this issue if not.
