### ISSUE TITLE
30+ umbrella header warnings

### ISSUE THREAD

**Issue by jeffepic** [krzyzanowskim/ObjectivePGP#154]
- ObjectivePGP version: 0.13.0
- Platform (iOS/macOS): iOS 9+
- Installation method (CocoaPods/Carthage/...): CocoaPods

# Description
I get 30+ umbrella header warnings in Xcode 10.2/10.3. It seems that public files are required to be in the umbrella header? I don't really understand. Has anyone else seen this?

<img width="301" alt="Screen Shot 2019-07-24 at 11 04 22 PM" src="https://user-images.githubusercontent.com/52935188/61849886-8eabd080-ae67-11e9-8ed4-0eed6182d565.png">

**Comment by tobiasjungnickel** [comment]
same for me
