### ISSUE TITLE
How to revoke a key?

### ISSUE THREAD

**Issue by p-barabas** [krzyzanowskim/ObjectivePGP#161]
- ObjectivePGP version: 0.14.0
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name:

# Description

In my application, where are situations when user should generate new key pair and revoke the old one. In PGP a revocation certificate is needed for this. Is it generated automatically internally when a key pair is generated? How can I generate the revoked pubic key which I need to upload to the server?

**Comment by krzyzanowskim** [comment]
>  In PGP a revocation certificate is needed for this. Is it generated automatically internally when a key pair is generated

The revocation signature is not generated automatically (and in fact, there's no public API to make one). You can use the `gpg` feature and edit a key, see http://sidgan.me/technical/2015/01/05/creating-and-revoking-gpg-keys
