### ISSUE TITLE
Can't import public key from VKS

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#162]
- ObjectivePGP version: 0.15.0
- Platform (iOS/macOS): 13.1.3
- Installation method (CocoaPods/Carthage/...): CocoaPods

# Description
When importing a public key from a Verifying Keyserver (VKS)
`ObjectivePGP.readKeys`
return 0 keys. The only difference seems to be that VKS keys starts with
`----`
while HKP keys starts with
`-----`.

# Steps to reproduce

Import of attached publicKey_VKS_1.asc doesn't work byt publicKey_VKS_2.asc does.

[Archive.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/3756099/Archive.zip)

**Comment by krzyzanowskim** [comment]
what happened?

**Comment by tobiasjungnickel** [comment]
sorry, was an error on our app and not ObjectivePGP. Can be deleted.
