### ISSUE TITLE
Can't read keys. Invalid input.

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#166]
- ObjectivePGP version: 0.15.0
- Platform (iOS/macOS): iOS 13.2
- Installation method (CocoaPods/Carthage/...): CocoaPods

# Description
When trying to read the attached key i get the following error
`[ObjectivePGP] ERROR: +[ObjectivePGP readKeysFromData:error:]/676 Invalid input data
Error: Error Domain=com.objectivepgp Code=9 "Can't read keys. Invalid input." UserInfo={NSLocalizedDescription=Can't read keys. Invalid input.}`
Importing this key works with other apps like GPGTools.
The only difference to other keys i see that it has no subkeys.

[key.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/3850436/key.asc.zip)

# Steps to reproduce

Sample code to reproduce the issue:

```objective-c

try ObjectivePGP.readKeys(fromPath: url.path)

```

**Comment by krzyzanowskim** [comment]
Thanks. I can reproduce. This is due to additiona empty line in the message, kinda unexpected and parser is failing

<img width="104" alt="Screenshot 2019-11-23 at 09 29 34" src="https://user-images.githubusercontent.com/758033/69475962-c99d2100-0dd3-11ea-8996-0c6f312ca7e4.png">
