### ISSUE TITLE
Support for PGP/MIME *feature request*

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#169]
Compose & decompose PGP/MIME

**Comment by krzyzanowskim** [comment]
How would that support look like?

**Comment by tobiasjungnickel** [comment]
my idea would be "simply" when passing an array of texts and files in any combination with an additional pgp-mime parameter to the encrypt method to return a data containing the full PGP/MIME content - and vice versa für decryption.

**Comment by krzyzanowskim** [comment]
you want to add MIME parser to extract PGP message from email message? be my guest. I'm looking forward to see it.
