### ISSUE TITLE
Unable to add ObjectivePGP using CocoaPOD

### ISSUE THREAD

**Issue by Ketan-Intelliquity** [krzyzanowskim/ObjectivePGP#170]
- ObjectivePGP version: 0.15.0
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods
- Project name:

# Description

Unable to add ObjectivePGP using CocoaPOD

Showing Recent Messages
'/PGPLibrarayIntegration/Gitlab/deVere-Vault/Code_base/Pods/ObjectivePGP/Frameworks/ios/ObjectivePGP.framework/ObjectivePGP' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/ics.ketan.malu/Desktop/PGPLibrarayIntegration/Gitlab/deVere-Vault/Code_base/Pods/ObjectivePGP/Frameworks/ios/ObjectivePGP.framework/ObjectivePGP' for architecture arm64

**Comment by krzyzanowskim** [comment]
One of the core dependency (OpenSSL) cannot be built with bitcode, therefore it won't work for ObjectivePGP as well.

I advise disable bitcode. Disabling bitcode currently does not have any known downsides for iOS apps.

ref https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication#bitcode

**Comment by Ketan-Intelliquity** [comment]
Thank you for such quick reply. Hope disabling bitcode will not affect symbolicate crash & submitting app to app store.

**Comment by Ketan-Intelliquity** [comment]
I already have public key in my app & private key on server to decrypt. How to encrypt string message using public key

**Comment by Ketan-Intelliquity** [comment]
Hello @krzyzanowskim sir can you please guide me if I can convert public key provided to me to PGPKey type??
