### ISSUE TITLE
Encrypt with a key and sign with a different key

### ISSUE THREAD

**Issue by punto2018** [krzyzanowskim/ObjectivePGP#175]
- ObjectivePGP version: 0.15.0
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoaPods

Hi everybody,
as for my understanding when a user want to send a message with bot encryption and signature it is needed:
- encrypt with the pub key of the receiver
- sign with the private key of the recipient

The following API,
NSData *encrypted = [ObjectivePGP encrypt:data addSignature:YES usingKeys:keys passphraseForKey:nil error:nil];

Take an NSArray of keys, but what is used for encryption, what is used for signature?

Any advice? 
Thanks

**Comment by krzyzanowskim** [comment]
a key consists of dedicated subkeys, one for encryption other one for signature (the actual configuration may vary, and depends on the setup used during key generation process)
