### ISSUE TITLE
[ObjectivePGP] WARNING: Can't use Key

### ISSUE THREAD

**Issue by sohamb1390** [krzyzanowskim/ObjectivePGP#177]
@krzyzanowskim 
While decrypting a message using `PGPKey` this method is throwing an error:
```
ObjectivePGP.decrypt(encryptedData, andVerifySignature: true, using: keys, passphraseForKey
```

**Error/Warning:**

```
[ObjectivePGP] WARNING: +[ObjectivePGP decryptPackets:usingKeys:passphrase:error:]/185 Can't use key "EEEB24FCC5B51E609BECFBE69785AD13B4BD3EBF".
Decrypted hash mismatch, invalid passphrase.
```
Any leads?

**Comment by krzyzanowskim** [comment]
Not enough information to debug this case. It may be invalid passprase provided. I'm closing it for now, feel free to re-open with more details like a key and password to reproduce it on my side.
