### ISSUE TITLE
Linker error Widget Extension

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#179]
- ObjectivePGP version: 0.15.0
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/Carthage/...): CocoPods

# Description
When adding a new Widget Extension target i get the same linker error for each other target (app and extension):
`ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/xxx/app/Pods/ObjectivePGP/Frameworks/ios/ObjectivePGP.framework/ObjectivePGP' for architecture arm64`

**Comment by krzyzanowskim** [comment]
Xcode 12, simulator arm target? yea, need to build it with Xcode 12 for that

**Comment by tobiasjungnickel** [comment]
running on a device works. Using latest Xcode 12 beta. Can you tell me what to change to be able to run it in the simulator as well?

**Comment by tobiasjungnickel** [comment]
adding "arm64" to the "Excluded Architectures" as "Any iOS Simulator SDK" in "Build Settings" for all app/extension targets solved it in Xcode 12 beta 6.

https://developer.apple.com/forums/thread/657913
