### ISSUE TITLE
iOS hangs when trying to decrypt non encrypted data

### ISSUE THREAD

**Issue by joshsmoore** [krzyzanowskim/ObjectivePGP#18]
Thanks for the help so far and the library.  

I am sorry to say that I am going to have to ask another newbie question.  I am experimenting with error handling so I thought I would pass in some plan text to decrypt just to see what happened.  I have pasted the code in question below

``` objectivec
    NSError *error = nil;

    NSData *decryptedData = [pgp decryptData:[@"asdf" dataUsingEncoding:NSUTF8StringEncoding] passphrase:nil error:&error];
    if (decryptedData && !error) {
        NSLog(@"decryption success");
        NSLog(@"%@", [[NSString alloc] initWithData:decryptedData encoding:NSUTF8StringEncoding]);

    } else {
        NSLog(@"%@", error);
    }
```

I expected the error object to be updated and for the else part of the if statement to be executed.  Instead the entire thread hangs and never seams to unhang.  Is this something I am doing wrong not handling it correct? Or is this a bug?

Thanks,

Josh

**Comment by jlalvarez18** [comment]
The problem with this scenario is you are trying to decrypt data that is not in the proper format.

With that being said, this method should fail gracefully and return an appropriate error. 

@krzyzanowskim correct me if I'm wrong :)

**Comment by joshsmoore** [comment]
Yes, I figured something like that was the problem, but as I am going to try to actually write an application that uses ObjectivePGP and plan to let users decrypt files I would like someway to gracefully recover from bad input.

**Comment by krzyzanowskim** [comment]
is this still a thing with the latest release?
