### ISSUE TITLE
超大文件进行PGP签名校验时会崩溃，原因是对NSData进行了copy操作

### ISSUE THREAD

**Issue by jiang374033014** [krzyzanowskim/ObjectivePGP#182]
- ObjectivePGP version: 
- Platform (iOS/macOS): 
- Installation method (CocoaPods/Carthage/...): 
- Project name:

# Description

# Steps to reproduce

Sample code to reproduce the issue:

```objective-c

// Code goes here

```

**Comment by krzyzanowskim** [comment]
Please use English. If google translate is right here, the problem you report is known and tracked, unfortunately, there's no easy solution.
