### ISSUE TITLE
[Apple Silicon] [iOS Simulator] Getting Build Error: `Undefined symbol: "_OBJC_CLASS_$_ObjectivePGP"`

### ISSUE THREAD

**Issue by gopal-epic** [krzyzanowskim/ObjectivePGP#184]
- ObjectivePGP version: '0.13.0'
- Platform (iOS/macOS): iOS
- Installation method (CocoaPods/SPM/...): CocoaPods

# Description
Getting Build Error: `Undefined symbol: "_OBJC_CLASS_$_ObjectivePGP"` when i try to build the project for iOS Simulators on Xcode 12.3, Apple Silicon Mac Mini.

# Steps to reproduce

~ Install Xcode 12.3 on Apple Silicon Mac or Mac Mini.
~ Open you project in Xcode.
~ Install ObjectivePGP cocoapod.
~ Clean Build Your Project.
~ Run your project on any iOS Simulator you would see the Build Error => `Undefined symbol: "_OBJC_CLASS_$_ObjectivePGP"`

Note:
~ The project builds fine when i try to run it on a Device(i.e. iPhone or On My Mac Mini).
~ I tried different solutions on web => playing around with active architectures, but none of them really helped.

**Comment by krzyzanowskim** [comment]
Interesting, I'd say the ARM slice for Simulator is there

<img width="282" alt="Screen Shot 2021-01-08 at 02 44 55" src="https://user-images.githubusercontent.com/758033/103964377-9b0b1280-515b-11eb-8fd7-8dde060e4f6f.png">

**Comment by gopal-epic** [comment]
Another interesting take away:

[Created On Apple Silicon Mac Mini.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/5785070/Created.On.Apple.Silicon.Mac.Mini.zip)
[Created On Intel MacBook Pro.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/5785071/Created.On.Intel.MacBook.Pro.zip)

**Comment by gopal-epic** [comment]
Getting latest version(i.e. 0.17.0) of ObjectivePGP solved it for me.
