### ISSUE TITLE
crash bug: importKey fails with a NSInvalidArgumentException exception 

### ISSUE THREAD

**Issue by chrisDwarner** [krzyzanowskim/ObjectivePGP#19]
I am trying to import a PGP public key and I get the following exception from imporKeysFromFile and importKey.  

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteData pgpCRC24]: unrecognized selector sent to instance 0x7fb72d410570'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cfc5c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010cc5ebb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010cfcd0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010cf2313c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010cf22cd8 _CF_forwarding_prep_0 + 120
	5   lithomobilus                        0x000000010c3ffff5 +[PGPArmor readArmoredData:error:] + 1905
	6   lithomobilus                        0x000000010c3fcc0e -[ObjectivePGP convertArmoredMessage2BinaryWhenNecessary:] + 250
	7   lithomobilus                        0x000000010c3fc36b -[ObjectivePGP keysFromData:] + 36
	8   lithomobilus                        0x000000010c3fbd24 -[ObjectivePGP importKeysFromData:allowDuplicates:] + 47
	9   lithomobilus                        0x000000010c3fbcc2 -[ObjectivePGP importKeysFromFile:allowDuplicates:] + 155

I traced the crash into PGPArmor (very painful without the source code!!!) and it appears when you attempt to perform a CRC check on the key data I think... 

Any assistance would be helpful.

**Comment by chrisDwarner** [comment]
forgot to add, this is with the latest IOS 8.3, in a simulator on Xcode 6.3(6D570)

**Comment by krzyzanowskim** [comment]
you need -ObjC parameter for linker to import external Objective-C categories.

Check README for details:
https://github.com/krzyzanowskim/ObjectivePGP/blob/0.3.2/README.md
