### ISSUE TITLE
cannot encrypt JSON data 

### ISSUE THREAD

**Issue by chrisDwarner** [krzyzanowskim/ObjectivePGP#20]
Trying to encrypt a small JSON block with ObjectivePGP using a public key that was generated off our servers using OpenPGP as implemented in Java via bouncycastle.org.

I have created a sample project that demonstrates the problem and uploaded it here:
https://github.com/chrisDwarner/ObjectivePGPSample

Looking at the PGPKey in the debugger, and it appears that the public key is loaded and parsed.
![screencapture](https://cloud.githubusercontent.com/assets/2755685/7149210/77b04690-e2bf-11e4-9aee-56d6aab23fae.png)

The encryption always fails with this error
2015-04-14 15:55:38.222 ObjectivePGPSample[21840:849105] {"email":"asdf","name":"oiuoiu","password":"l;k;kj"}
2015-04-14 16:01:57.520 ObjectivePGPSample[21840:849105] error encrypting data Error Domain=ObjectivePGP Code=0 "Encryption key not found" UserInfo=0x7fa7b8650c80 {NSLocalizedDescription=Encryption key not found}

**Comment by krzyzanowskim** [comment]
Did you imported public key?

**Comment by chrisDwarner** [comment]
yes, take a look at the sample.  I imported the key with a call to  importKeysFromFile.  It looks like the key was successfully imported, I can look up the key with the PGPUserId and find the key.

**Comment by chrisDwarner** [comment]
Here is the code that I use to encrypt
`        // encrypt the JSON string with the public server key into a NSData block
        ObjectivePGP *pgp = [[ObjectivePGP alloc] init];
        
        if (pgp) {
            NSArray *pgpServerKeys = [pgp importKeysFromFile:serverKeysPath allowDuplicates:NO];
            
            // getKeysForUserID returns a NSArray
            NSArray *pgpKeys = [pgp getKeysForUserID:@"bookstore server"];
            
            // There is only one key, so we use it.
            PGPKey  *pgpKey = [pgpKeys objectAtIndex:0];
            
            if (pgpKey) {
                NSError *error = nil;

                NSData *encryptedData = [pgp encryptData:jsonData usingPublicKey:pgpKey armored:YES error:&error];
                if (encryptedData && !error) {
                    // export NSData block into ASCII armored package
                    // success, transmit the data
                    NSString *EncrypedString = [[NSString alloc] initWithBytes:[encryptedData bytes] length:[encryptedData length] encoding:NSUTF8StringEncoding];
                    NSLog(@"%@",EncrypedString);
                }
                else {
                    NSLog(@"error encrypting data %@", error);
                }
            }
            else {
                NSLog(@"no public key found");
            }
        }
`

**Comment by krzyzanowskim** [comment]
It may be that the key here is the key :-) Is it possible to reproduce issue with another key? Is fo I would take a look inside that key

**Comment by krzyzanowskim** [comment]
"Encryption key not found" error suggest that given key may be not suitable to encrypt data. Keys have flags, this is why I would like to see similar key to verify.

**Comment by chrisDwarner** [comment]
I tried to verify the key using GnuPGP 1.2b6(1057b).  I first imported the key into the GnuPGP keychain, then using the command line tools I was able to generate an armored encrypted document.  However, this was not without a warning, which might be our problem here.  

```
NT-MacBookilus:~ chriswarner$ gpg2 --armor --recipient 'bookstore server' --encrypt testmsg.txt
gpg: E748B4DD: There is no assurance this key belongs to the named user
pub  rsa2048/E748B4DD 2015-04-07 bookstore server
 Primary key fingerprint: B9B0 24CE B599 A115 F7F7  99DB AB01 90AF FDD2 FE3E
      Subkey fingerprint: 16CA ED86 372A 4CA6 EBB2  3F13 837A 2DB6 E748 B4DD

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
NT-MacBookilus:~ chriswarner$ ls
Applications		Library			dev
Desktop			Movies			ios-static-libraries
Documents		Music			lithomobilus
Downloads		Pictures		testmsg.txt
Dropbox			Public			testmsg.txt.asc
```

gpg has labeled this as a weak key, could this be part of the problem?

**Comment by krzyzanowskim** [comment]
not sure. It may be, or.. there is a flag that is checked. Can you issue new key like this ?

**Comment by chrisDwarner** [comment]
I am looking at the code used to create the PGP key.  
we are creating a PGPPublicKey with RSA_SIGN key set.  This key also has a sub PGPKeyPair with the key flags set for RSA_Encrypt key set.  The key pair data for both keys is randomly generated.

The meta data on the signature for the primary PGPKey has the following flags SIGN_DATA | CERTIFY_OTHER
preferred symmetric algorithems AES_256
preferred hash algorithems SHA256

the sub-key has ENCRYPT_COMMS | ENCRYPT_STORAGE

**Comment by krzyzanowskim** [comment]
ok, just a suggestion, stop looking at generation code, simply generate new test key and send it to me ;) I can't tell anything more at the moment.

**Comment by chrisDwarner** [comment]
I have tried using keys created manually with both macPGP and GnuPGP and the code works.  For what ever reason the keys we generate on our server through code are not working with the library.

**Comment by krzyzanowskim** [comment]
srsly @chrisDwarner this is the last time I'll ask you for the generated key to take a look ;) If you cannot provide one, my work is done here.
