### ISSUE TITLE
Export Secret Keys

### ISSUE THREAD

**Issue by dstan2** [krzyzanowskim/ObjectivePGP#22]
--edited--

I am having an issue with the command:
[_pgp exportKeysOfType:PGPKeySecret toFile:secringPath error:&exportError];

I've found that a secret key exported with this command is different than it was when it was imported. 
The differences between the original secret key on the left, and the secret key after export on the right, can be seen here: 
https://www.diffchecker.com/nffk6ulu

The impact of this difference is that the secret key's passphrase no longer works, so the secret key becomes useless. (The passphrase for this key is "weakpassphrase")

This leads me to a follow up question - How can a secret key ring be saved?

**Comment by dstan2** [comment]
@krzyzanowskim any input on this? I've been stuck here for weeks

**Comment by krzyzanowskim** [comment]
The essence is identical on both, though one of the exported packets is 20 bytes longer... trying to find out why
