### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by blairmacintyre** [krzyzanowskim/ObjectivePGP#23]
If I try using the library in my project, I get link errors.  I get the two below just linking with the libObjectivePGP.a, but if I add libcrypto.a and libssl.a, I get a ton more.  I suspect I'm doing something stupid, of have the project settings set up in such a way that it's causing these problems (I'm also using Qualcomm's Vuforia augmented reality library, which is compiled in such a way that I had to change the way I'm compiling things, because of their compile conventions).

Any ideas what would cause this? 
```duplicate symbol _OBJC_CLASS_$_PGPSecretSubKeyPacket in:
    /Users/blair/Desktop/programming/github/argon-app/iOS/Dependencies/objectivePGP/lib-ios/libObjectivePGP.a(PGPKey.o)
    /Users/blair/Desktop/programming/github/argon-app/iOS/Dependencies/objectivePGP/lib-ios/libObjectivePGP.a(PGPSecretSubKeyPacket.o)
duplicate symbol _OBJC_METACLASS_$_PGPSecretSubKeyPacket in:
    /Users/blair/Desktop/programming/github/argon-app/iOS/Dependencies/objectivePGP/lib-ios/libObjectivePGP.a(PGPKey.o)
    /Users/blair/Desktop/programming/github/argon-app/iOS/Dependencies/objectivePGP/lib-ios/libObjectivePGP.a(PGPSecretSubKeyPacket.o)```

I include the header:
```#import "ObjectivePGP.h"```
and am have a very simple function to do decryption:
```
-(NSDictionary*)decryptEncryptedJSON:(NSString*) encryptedJSON withPassword:(NSString*)password
{
    ObjectivePGP *pgp = [[ObjectivePGP alloc] init];
    [pgp importKeysFromFile:@"argonjs-priv.asc" allowDuplicates:NO];
    NSError *error = nil;
    NSData *decryptedJSON = [pgp decryptData:[encryptedJSON dataUsingEncoding:NSUTF8StringEncoding] passphrase:password error:&error];
    if (decryptedJSON && !error) {
        NSLog(@"decryption success");
    } else {
        NSLog(@"decryption error => %@ ", [error localizedDescription] );
    }
    NSDictionary *decryptedData = nil;
    if (decryptedJSON) {
        NSError *jsonError=nil;
        decryptedData = [NSJSONSerialization JSONObjectWithData:decryptedJSON
                                                        options: 0
                                                        error: &jsonError];
        if (jsonError || ![decryptedData isKindOfClass:[NSMutableDictionary class]]) {
            NSLog(@"Error parsing options");
            return nil;
        }
    }
    return decryptedData;
}
```

**Comment by blairmacintyre** [comment]
A bit more clarification.  I went back to my working project before adding this library.  I added the .a file to it and get conflicts.  

The project builds (first) a static library, where the decryption is done, and then builds an app with it.  I link the objectivePGP.a with the .a I build.  I have also tried linking it with the app.  I get these errors regardless.

**Comment by blairmacintyre** [comment]
Arg.  One of the folks working on the project had added a "-all_load" flag to the linker flags, which seems to be what caused the problem.

**Comment by krzyzanowskim** [comment]
👍

**Comment by blairmacintyre** [comment]
FYI, after I solved this stupid problem, I got things working pretty quickly.  I can now encrypt data with a public key I created for my app (using PGPTools), put it on the web somewhere, download it into my app,  and decrypt it with the embedded secret key.  Works like a charm.  Thanks for the library!  

In case you care about who's using it and why, the app in question is our Augmented Reality web browser for iOS, Argon.  I'm working on finishing up the 3rd version, Argon3, which we'll release on iOS soon ... and also as open source on github at argonjs.io. We need encryption because we're using Qualcomm's Vuforia AR software, and we need people to pass their license key into the browser, but we don't want them to put their key's in plaintext on the web.  So we have them encrypt it, along with a set of "allowable URLs to use it from", in a JSON file (sort of a poor mans CORS).

You can see some info on the old version at argon.gatech.edu, if you care; the old Argon and Argon2 Isotope apps are still on the store.
