### ISSUE TITLE
Error decrypt Error Domain=ObjectivePGP Code=0 "Missing session key data"

### ISSUE THREAD

**Issue by carlosgarciaa** [krzyzanowskim/ObjectivePGP#24]
Error decrypt Error Domain=ObjectivePGP Code=0 "Missing session key data" UserInfo=0x7aef2ea0 {NSLocalizedDescription=Missing session key data}
2015-07-05 02:56:09.630 test3DES[7263:389779] paso10: Error decrypt Error Domain=ObjectivePGP Code=0 "Missing session key data" UserInfo=0x7aef2ea0 {NSLocalizedDescription=Missing session key data}

the text was encrypt in java with bounce castle, can I help for resolve this problem, please.
When I encrypted from iOS and Objective PGP, the decrypt is ok.

Code:
    
    ObjectivePGP *pgp = [[ObjectivePGP alloc] init];

    [pgp importKeysFromData:[publicKey dataUsingEncoding:NSUTF8StringEncoding] allowDuplicates:YES];
    [pgp importKeysFromData:[privatekey dataUsingEncoding:NSUTF8StringEncoding] allowDuplicates:YES];

    PGPKey *key = [[pgp getKeysOfType:PGPKeyPublic] objectAtIndex:0];
    PGPKey *pkey = [[pgp getKeysOfType:PGPKeySecret] objectAtIndex:0];

    NSString * clave = @"clave";
    NSString * textocifrado = [self readFile:@"encryptBC4" type:@"txt"];
    NSData * decryptedData = [pgp decryptData:[textocifrado dataUsingEncoding:NSUTF8StringEncoding] passphrase:clave error:&error];

    if (decryptedData && !error) {
        NSLog(@"decryption success %@", [[NSString alloc] initWithData:decryptedData encoding:NSUTF8StringEncoding ]);
        resp = [[NSString alloc] initWithData:decryptedData encoding:NSUTF8StringEncoding ] ;
    }
    else {
        NSLog(@"Error decrypt %@",error);
        resp = [NSString stringWithFormat:@"Error decrypt %@",error] ;
    }

**Comment by krzyzanowskim** [comment]
It seems fixed with latest changes. Feel free to reopen this issue if not.
