### ISSUE TITLE
Decryption without issue and without result

### ISSUE THREAD

**Issue by alexkunitsa** [krzyzanowskim/ObjectivePGP#25]
Hi! 
I have some problems when decoding message, that was not encoded by ObjectivePGP.
If message was encoded with your library, there is no issues and I can get text that was encoded.
But if it was encoded with f.e. Thunderbird Enigmail plugin or with other service:

```swift
let objectivePGP = ObjectivePGP()
var error: NSError?
let decryptedMessageData = objectivePGP.decryptData(textData, passphrase: passphrase, error: &error) {
    if (decryptedMessageData != nil && error == nil) {
        println("success")
    } else {
        println("fail")
    }
}
```
There is no issues while decoding and I see "success", but decryptedMessageData  is NSData with 0 bytes. What can be the reason and can it be fixed? Please advise.

**Comment by alexkunitsa** [comment]
Looks like issue is somewhere in PGPLiteralPacket. 
When parsePacketBody:: is called, there is switch, and it never gets here:

```
switch (self.format) {
        case PGPLiteralPacketBinary:
        {
          // here
        }
...
```

so, literalRawData is never set

**Comment by alexkunitsa** [comment]
So, looks like I found fix for my case.

Class PGPLiteralPacket, method parsePacketBody:: contains format switch of self.format. For unknown reason when decoding data from our service (or from Thunderbird Enigmail), it fails (we receive empty string from zero data). 

When we parse that data, we get to that case 
```
case PGPLiteralPacketTextUTF8:
```
but as a result we have empty string as output.
It works if replace that switch with:

```
self.literalRawData = [packetBody subdataWithRange:(NSRange){position, packetBody.length - position}];
```

**Comment by krzyzanowskim** [comment]
If you have a fix, please submit PR

**Comment by krzyzanowskim** [comment]
@alexkunitsa do you have sample files that cause problem, by any chance ?

**Comment by krzyzanowskim** [comment]
I think this issue has been addressed some time ago. It is not possible to not set `literalRawData` unless input type is invalid.
