### ISSUE TITLE
ObjectivePGP doesn't appear to like keys generated by UNNetPGP

### ISSUE THREAD

**Issue by ozobken** [krzyzanowskim/ObjectivePGP#27]
I'm writing an iOS app that needs to generate its own keys, and as ObjectivePGP doesn't do that, I thought I'd use your other library just for the keygen - which all works, and ObjectivePGP imports the keys fine, but calls to encryptData: fail with "Encryption key not found"

ObjectivePGP happily uses Keybase or gpg2 keys, and gpg2 is happy with the UNNetPGP keys

Any thoughts?

**Comment by rajarajeswari-mathivanan** [comment]
Hi,
Even I am facing the same issue.How to use the keys generated from UNNetPGP in Objective PGP.Please help

**Comment by alexkunitsa** [comment]
Hi,
same for me. If you know any way to generate pgp keys on iOS, please advice

**Comment by emayevski** [comment]
SecureBlackbox ( https://www.eldos.com/sbb/ ) offers full scope of OpenPGP functionality including generation of OpenPGP keys, and can be used in Objective C, Swift, C# (Xamarin) and Pascal applications for iOS.

**Comment by ozobken** [comment]
https://github.com/gabriel/KBPGP from the Keybase guys looks promising, but needs a bit of caking to build - and as the engine is JS, the keygen is slow - for testing/eval, it's worth a look

**Comment by ozobken** [comment]
I can confirm that KBPGP keys work fine in Objective PGP :)
Be really nice to have a native, keygen though - love your work, Marcin
