### ISSUE TITLE
Decryption of image and file size greater than 3 kb

### ISSUE THREAD

**Issue by rajarajeswari-mathivanan** [krzyzanowskim/ObjectivePGP#28]
Hi 
I am not able to encrypt file size greater than 3 kb using Objective PGP and with further look at the issues section went ahead and changed  compression library to PGPCompressionZLIB .After that i was able to see encrypted content but its failing while decrypting.There was an issue while building the body length and packet data is lesser than finalBodyLength out of which rangeexception is thrown..is there any way we can solve this..

 else if (firstOctet == 255) {
        // 4.2.2.3.  Five-Octet Length
        // bodyLen = (2nd_octet << 24) | (3rd_octet << 16) |
        //           (4th_octet << 8)  | 5th_octet
        bodyLength   = (lengthOctets[1] << 24) | (lengthOctets[2] << 16) | (lengthOctets[3] << 8)  | lengthOctets[4];
        headerLength = 1 + 5;
    }

Also when i try to encrypt/decrypt an image its not working..Could you please suggest how to go about this issue.

**Comment by krzyzanowskim** [comment]
Fixed by https://github.com/krzyzanowskim/ObjectivePGP/pull/31
