### ISSUE TITLE
Encryption error when file is larger then 8383 bytes and crash when trying to decrypt

### ISSUE THREAD

**Issue by ghaarsma** [krzyzanowskim/ObjectivePGP#29]
When trying to encrypt a file larger then 8383 bytes an incorrect new format (Five-Octet Lengths) packet length is written.

In "PGPPacket.m" on lines 263:266 the single octet holding the value 255 is written twice.
```objectivec
UInt8 marker = 255;
[data appendBytes:&marker length:1];

buf[0] = 0xff;
```
Commenting out lines 263/264 fixes the bug.

When trying to decrypt an file with incorrect packet header, the GnuPG software strips the first 121 characters of the file away.

When trying to decrypt an file with incorrect packet header with the ObjectivePGP library it crashes in "PGPPacketFactory.m" when executing line 54:
```objectivec
NSData *packetBodyData = [packetData subdataWithRange:(NSRange) {offset + packetHeaderData.length, finalBodyLength}];
```
Because of the corrupt header, `definedBodyLength` is much to large. Should perhaps do a sanity check on `definedBodyLength` and report an error when it's larger then length of the packet data. Seems like there are multiple crash reports/issues related to this.

Gabe

**Comment by krzyzanowskim** [comment]
willing to create PR for review?

**Comment by ghaarsma** [comment]
Created a PR. First time I did this for me. Let me know if this works for you.

**Comment by krzyzanowskim** [comment]
thx will review shortly

**Comment by krzyzanowskim** [comment]
fixed by https://github.com/krzyzanowskim/ObjectivePGP/pull/31
thanks!
