### ISSUE TITLE
Encryption key not found

### ISSUE THREAD

**Issue by aetsyss** [krzyzanowskim/ObjectivePGP#30]
Hi! Please help me...
What am I doing wrong?
So, I've created 2 keys using https://www.igolder.com/pgp/generate-key/
and imported them into my project.

Then wrote a code:

```
    let pgp = ObjectivePGP()
    // load keys
    pgp.importKeysFromFile(publicFilename!, allowDuplicates: false)
    pgp.importKeysFromFile(privateFilename!, allowDuplicates: false)

    let keys = pgp.getKeysForUserID("mymail@gmail.com")
    let keyToEncrypt = keys.first as! PGPKey

    do {
        let encryptedData = try pgp.encryptData(fileContent!, usingPublicKey: keyToEncrypt, armored: true)
        print(encryptedData)
    } catch let error as NSError {
        print(error)
    }
```

And it prints "Error Domain=ObjectivePGP Code=0 "Encryption key not found" UserInfo={NSLocalizedDescription=Encryption key not found}"

**Comment by krzyzanowskim** [comment]
first of all check if key's are there after you `importKeysFromFile` and see it it's importer properly. You can share the public key so I can investigate the issue.
