### ISSUE TITLE
can not decrypt file in openpgp after encrypt by objectivePGP

### ISSUE THREAD

**Issue by seteda54** [krzyzanowskim/ObjectivePGP#34]
I use your objectivePGP to encrypt text data follow this code on iOS:
```
NSError *error = nil;

NSData *fileContent = [NSData dataWithContentsOfFile:@"/path/file/to/data.txt"];

/* public key to encrypt data, must be loaded previously */
PGPKey *keyToEncrypt = [self.oPGP getKeyForIdentifier:@"979E4B03DFFE30C6" type:PGPKeyPublic];

/* encrypt data, armor output (ASCII file)  */
NSData *encryptedData = [pgp encryptData:fileContent usingPublicKey:keyToEncrypt armored:YES error:&error];
if (encryptedData && !error) {
    NSLog(@"encryption success");
    [encryptedData writeToFile:@"/path/to/encrypted/file.gpg" atomically:YES]
}
```
But when I decrypt it with openPGP, It has error about bzip2 and I can not decrypt file. But in iOS, it's normal.
Have you test this case with your library?

**Comment by seteda54** [comment]
I found that this is optional, to decrypt file with openpgp, I replace this code in ObjectivePGP.m:
PGPCompressedPacket *compressedPacket = [[PGPCompressedPacket alloc] initWithData:literalPacketData type:PGPCompressionBZIP2];
with this: 
PGPCompressedPacket *compressedPacket = [[PGPCompressedPacket alloc] initWithData:literalPacketData type:PGPCompressionZLIB];
So, this work fine!

**Comment by krzyzanowskim** [comment]
hm... this shouldn't be a case, can you share the encrypted message that cause such problem ?

**Comment by krzyzanowskim** [comment]
is this still a thing with the latest release?

**Comment by seteda54** [comment]
Dear Marcin Krzyanowski,
I will check again with your lastest release,
Thanks very much

2016-06-30 19:58 GMT+07:00 Marcin Krzyzanowski <notifications@github.com>:

**Comment by krzyzanowskim** [comment]
Shouldn't be a problem with version 0.6

**Comment by AlexEKoren** [comment]
I'm still running into this issue! OpenPGP is complaining about BZip2.

> Compression algorithm BZip2 [BZ2] is not implemented.

Is there a way to change the standard compression using the pod install or should I fork and make the changes?

**Comment by krzyzanowskim** [comment]
@AlexEKoren where do you get the warning like this? Don't see where it may come from now.

**Comment by AlexEKoren** [comment]
This was from the backend dev I work with. We altered OpenPGP to make it work although I don't have the exact specifics...
