### ISSUE TITLE
Application assert: reason: 'Partial body length is not fully supported'

### ISSUE THREAD

**Issue by MarkoN-Hexele** [krzyzanowskim/ObjectivePGP#36]
Hi,

I integrated your ObjectivePGP to my Mac command line application. All installation did well and my app compiled and started successfully. 

Main use for my Mac app is to decrypt externally generated encrypted pgp-file. So I am using secret key file to decrypt file and key is imported to SW correctly according to my debugging.

Problem is that ObjectivePGP "hangs" to assert.
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Partial body length is not fully supported'
***
What is this and what I am doing wrong?

I can't deliver data file or key file because these are secret ones in our case.

Any recommendations to try or should I deliver more data to help you?

Marko

**Comment by krzyzanowskim** [comment]
Looks like you're using old version. We don't have such error since 0.4.1

**Comment by MarkoN-Hexele** [comment]
Hi,

Thanks for your answer.

I am using ObjectivePGP version 0.4.2. This is a error print from xcode:

/logreader/Pods/ObjectivePGP/ObjectivePGP/PGPPacket.m:154
2016-06-29 20:35:32.915 logreader[2228:667258] *** Terminating app due  
to uncaught exception 'NSInternalInconsistencyException', reason:  
'Partial body length is not fully supported'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8ea334f2  
__exceptionPreprocess + 178

snippet of code:
*length = bodyLength;

     NSAssert(!isPartialBodyLength, @"Partial body length is not fully  
supported");
     NSAssert(bodyLength > 0, @"The packet is of indeterminate length");

     return headerLength;

Hope this helps,

BR,
Marko Nousiainen

Lainaus Marcin Krzyzanowski <notifications@github.com>:

**Comment by krzyzanowskim** [comment]
go with v. 0.5
