### ISSUE TITLE
"Unsuported subpacket type 32" when initializing secret key

### ISSUE THREAD

**Issue by MarkoN-Hexele** [krzyzanowskim/ObjectivePGP#38]
Hi,

Thank You very much for this software package.

I did not manage to decrypt file by using secret key file. This secret file is generated in Linux system. Here are some additional details:
Using ObjectivePGP (0.5)
Using OpenSSL-Universal (1.0.1.19)

My test SW:
ObjectivePGP *pgp = [[ObjectivePGP alloc] init];
/* Import key from file */
[pgp importKeysFromFile:@"/Users/Marko/secret_key.asc" allowDuplicates:NO];

* When running SW to here there is a "log" message "Unsuported subpacket type 32"
* When running SW further, next line is of course just fine
NSData *encryptedFileContent = [NSData dataWithContentsOfFile:@"/Users/Marko/encrypted.gpg"];

* This method returns always nil
NSData *decryptedData = [pgp decryptData:encryptedFileContent passphrase:@"password" error:&error];

I can't deliver encrypted file or secret key file because we are using those in our production.
Any comments or helps?

**Comment by krzyzanowskim** [comment]
Can't help you with that one. It may be anything. Without message to reproduce it's not possible to debug.
