### ISSUE TITLE
Compiling problem: dublicate symbols

### ISSUE THREAD

**Issue by pangers** [krzyzanowskim/ObjectivePGP#40]
Hi,

I seem to be having a problem compiling the project. It comes up with a:

`duplicate symbol _OBJC_CLASS_$_PGPSecretSubKeyPacket in:
    /Users/name/Library/Developer/Xcode/DerivedData/RMSRego-bqwuvgrpprlbwccmfexknldmdtku/Build/Products/Debug-iphoneos/libObjectivePGP.a(PGPKey.o)
    /Users/name/Library/Developer/Xcode/DerivedData/RMSRego-bqwuvgrpprlbwccmfexknldmdtku/Build/Products/Debug-iphoneos/libObjectivePGP.a(PGPSecretSubKeyPacket.o)
duplicate symbol _OBJC_METACLASS_$_PGPSecretSubKeyPacket in:
    /Users/name/Library/Developer/Xcode/DerivedData/RMSRego-bqwuvgrpprlbwccmfexknldmdtku/Build/Products/Debug-iphoneos/libObjectivePGP.a(PGPKey.o)
    /Users/name/Library/Developer/Xcode/DerivedData/RMSRego-bqwuvgrpprlbwccmfexknldmdtku/Build/Products/Debug-iphoneos/libObjectivePGP.a(PGPSecretSubKeyPacket.o)`

This is actually the same problem as #6 (towards the bottom), which actually has the solution:

> PGPKey.m was importing PGPSecretSubKeyPacket.m instead of PGPSecretSubKeyPacket.h.

So I changed the files according to the solution and sure enough the project compiles. However, this is a temporary solution as the version of the library obtained after 'pod install' is still broken. Are you able to fix this in the project? Or I can make a pull request if you'd like. Let me know.

Thanks for the library!

Cheers

**Comment by krzyzanowskim** [comment]
thanks!

**Comment by pangers** [comment]
@krzyzanowskim Are you able to update the project so when 'pod install' is run, my changes are observed? Even though the pull request has been merged, pod install still installs the old version.

**Comment by krzyzanowskim** [comment]
with the next release. For the time being, add branch: 'master' to Podfile

**Comment by pangers** [comment]
Hi @krzyzanowskim ,

I just wanted to follow up on if you have updated CocoaPods repository with this fix? I looked at the commits and I saw that you updated the podspec with 5.1.

However on the cocoapods website (https://cocoapods.org/?q=objectivepgp) Objective PGP is still on 5.0 and when I do pod install on a fresh project, I am still getting 5.0, which is without the fix.

Do you have an estimate of when this fix will be available?

**Comment by krzyzanowskim** [comment]
I had some troubles upload it to cocoapods spec. As a workaround you can use this:

```
pod 'ObjectivePGP', :git => "https://github.com/krzyzanowskim/ObjectivePGP", :branch => "master"
```
