### ISSUE TITLE
[Feature/Help] Support for Symmetric encryption

### ISSUE THREAD

**Issue by sergioabril** [krzyzanowskim/ObjectivePGP#43]
First of all, great library!
Not sure if this is included, since I can't find it documented; would be nice to have support for symmetric encrypted data, just using a passphrase (like using the "gpg -c xx.txt" on a Desktop), and keeping the PGP standards; in order to be able to decrypt and encrypt file/strings compatible with a regular GPG desktop implementation.

(Note: I'm perfectly able to symmetrically encrypt/decrypt data using your amazing CryptoSwift lib, but I can't figure out how to follow the PGP standards at the time of sharing the IV, the headers, etc... and would be nice the be able to work with PGP encrypted files across iOS/Desktop if this lib supported it).
Thanks, and keep up the good work!

**Comment by krzyzanowskim** [comment]
PGP is a protocol, while symmetric encryption is about ciphers. You need it both to have something like OpenPGP.

You could use plain AES within custom container in format IV:CIPHERTEXT, it's like this with various libraries - adds payload to store ciphertext along the metadata

**Comment by eiprol** [comment]
Thanks, that's what I ended up doing; it was just to keep compatibility and be able to decrypt/encrypt across Desktop GnuPG (with gpg -c option) and iOS with your ObjectivePGP. (Not for the cipher thing, but to generate the right header packets). But thanks!

**Comment by adammorley** [comment]
@sergioabril was this for your safy code?  either way, can you point me to your impl, I was looking at doing symmetric decryption of an ascii-armored gpg encrypted file (encrypted on linux, to decrypt on ios) and didn't want to re-invent the entire wheel.  thx
