### ISSUE TITLE
*Not* an issue, but a question: Security audit? 

### ISSUE THREAD

**Issue by motatoe** [krzyzanowskim/ObjectivePGP#45]
Has this implementation of OpenPGP ever undergone a security audit?  If so, where/when/from whom/etc.
Or, are there any prominent apps that have use ObjectivePGP?  Apart from Marcin himself, of course ;)
Thanks for any info.

**Comment by krzyzanowskim** [comment]
From what I know, I was audited, but it was handled internally by the company.
I can't afford security audit by myself.

**Comment by krzyzanowskim** [comment]
I'm closing this one. The security audit costs are around $40k, and I can't afford it. This is mainly a hobby project so far.
The prominent app... I don't follow; I know it is used. Recently [CanaryMail](https://canarymail.io/) deployed it.
