### ISSUE TITLE
Cannot use Carthage to include the framework

### ISSUE THREAD

**Issue by mssun** [krzyzanowskim/ObjectivePGP#47]
When I use Carthage to build the framework, it gives me this error:
```
*** Skipped building ObjectivePGP due to the error:
Dependency "ObjectivePGP" has no shared framework schemes
```

Is there any way I can use to include this framework in my project? Thanks.

**Comment by mssun** [comment]
Still cannot build with Carthage. I guess you have to add a *framework* scheme.

**Comment by krzyzanowskim** [comment]
wait. what framework?

**Comment by mssun** [comment]
Sorry, I mean add a framework target...

I'm not familiar with Carthage. From his documentation: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework, I saw that Carthage only officially supports dynamic frameworks.

**Comment by krzyzanowskim** [comment]
not gonna happen. there is static openssl dependency.

**Comment by mssun** [comment]
All right. Thanks.

BTW, I saw you are actively working on CryptoSwift. Is it possible to
implement PGP upon CrypotSwift?
