### ISSUE TITLE
Random suffix mismatch

### ISSUE THREAD

**Issue by asinoai** [krzyzanowskim/ObjectivePGP#48]
Hello!

I'm trying to use your library (which looks great by the way :) ), with the below code; the encryption works, but if I'm trying to decrypt it back, it will return nil.  I've debugged it a bit and I see that there is an error at one point with the message "Random suffix mismatch".
I've attached the pub- and secret-keyfiles. They are just for test and generated using bouncy castle from java.
Any feedback would be much appreciated!

p.s. I had to rename the files to have txt extensions, so I can attach it to this issue; thus the txt extension should be removed.

[pub.asc.txt](https://github.com/krzyzanowskim/ObjectivePGP/files/745953/pub.asc.txt)
[secret.asc.txt](https://github.com/krzyzanowskim/ObjectivePGP/files/745954/secret.asc.txt)

I forgot to mention that I modified PGPSignaturePacket.m to accept keys with no flags at all (gpg accepts it :) ), but I don't think this really changes anything:

```
- (BOOL)canBeUsedToSign
{
    BOOL result = self.publicKeyAlgorithm == PGPPublicKeyAlgorithmDSA || self.publicKeyAlgorithm == PGPPublicKeyAlgorithmRSA || self.publicKeyAlgorithm == PGPPublicKeyAlgorithmRSASignOnly;

    if (result) {
        PGPSignatureSubpacket *subpacket = [[self subpacketsOfType:PGPSignatureSubpacketTypeKeyFlags] firstObject];
        NSArray *flags = subpacket.value;
        if (!flags || [flags containsObject:@(PGPSignatureFlagAllowSignData)]) {
            return YES;
        }
    }
    return NO;
}

- (BOOL)canBeUsedToEncrypt
{
    BOOL result = NO;
    PGPSignatureSubpacket *subpacket = [[self subpacketsOfType:PGPSignatureSubpacketTypeKeyFlags] firstObject];
    NSArray *flags = subpacket.value;
    if (!flags || [flags containsObject:@(PGPSignatureFlagAllowEncryptStorage)] || [flags containsObject:@(PGPSignatureFlagAllowEncryptCommunications)]) {
        result = YES;
    }
    
    // I'm not convinced if DSA is allowed here self.publicKeyAlgorithm != PGPPublicKeyAlgorithmDSA
    result = result && self.publicKeyAlgorithm != PGPPublicKeyAlgorithmRSASignOnly && self.publicKeyAlgorithm != PGPPublicKeyAlgorithmElgamalEncryptorSign;
    
    return result;
}

```

The code that fails:

```

+ (NSData *)encode{

    NSData *data = [@"Just a sample!" dataUsingEncoding:NSUTF8StringEncoding];

    NSData* result = nil;

    NSString *publicKeyRingFilePath = [[NSBundle mainBundle] pathForResource:@"pub" ofType:@"asc"];
    NSData *publicKeyRing = [NSData dataWithContentsOfFile:publicKeyRingFilePath];

    NSString *secretKeyRingFilePath = [[NSBundle mainBundle] pathForResource:@"secret" ofType:@"asc"];
    NSData *secretKeyRing = [NSData dataWithContentsOfFile:secretKeyRingFilePath];

    ObjectivePGP *pgp = [[ObjectivePGP alloc] init];

    [pgp importKeysFromData:publicKeyRing allowDuplicates:YES];
    [pgp importKeysFromData:secretKeyRing allowDuplicates:YES];

    NSArray *keys = [pgp getKeysForUserID:@"webmaster@appselent.com"];

    NSUInteger count = [keys count];

    if (count == 2) {
        PGPKey *publicKey = [keys objectAtIndex: 0];
        PGPKey *privateKey = [keys objectAtIndex: 1];

        if ([privateKey type] == PGPKeyPublic) {
            PGPKey *temp = publicKey;
            publicKey = privateKey;
            privateKey = temp;
        }

        NSError* error = nil;
        result = [pgp encryptData:data usingPublicKey:publicKey armored:NO error:&error];


        NSData* verify = [pgp decryptData:result passphrase:@"hello" verifyWithPublicKey:nil signed:nil valid:nil integrityProtected:nil error:&error];

    }

    return result;
}
```

**Comment by asinoai** [comment]
I've tried to decrypt the message encrypted with the this library with gpg and it fails:
gpg: packet(3) with unknown version 118
gpg: WARNING: encrypted message has been manipulated!

**Comment by asinoai** [comment]
I debugged it a bit and it is very strange, in some cases it works, meaning the encrypted data does get decrypted and it correct too, i.e. it is the same data that was encrypted, but sometimes not

**Comment by krzyzanowskim** [comment]
Do you reproduce the issue without the changes you've made? It sounds like missing header or something similar, because version 118 does not exists AFAIR

**Comment by asinoai** [comment]
Without the changes I made, the encryption is not possible because the logic doesn't find any key to use to encrypt. But gnupg does find one - the only one - and it works fine, both the encryption and the decryption.

**Comment by asinoai** [comment]
Probably it is a corner case and I need to put in the keys more stuff like those missing flags; I saw that my keys are rather short. :) But as mentioned it worked fine with gnupg. Thanks for the feedback!

**Comment by krzyzanowskim** [comment]
I think that's the the thing:
>  An implementation SHOULD NOT create such a key, but MAY interpret it.

I don't apparently.

**Comment by asinoai** [comment]
I use this code to generate: https://gist.github.com/asinoai/d36946d1bdebe2076574d55a6c88690a

**Comment by asinoai** [comment]
But what is really strange that with my modifications, if I run the encode function e.g. 10 times, 2 times it will work correctly, but 8 times it will fail. Really strange.

**Comment by asinoai** [comment]
Btw. my main goal is to be able to encrypt with ios and decrypt with gnupg on linux (and generate keys with java).

**Comment by asinoai** [comment]
Good news! :) I've put the missing flags part into the keys and now it works without any problem: I was able to decrpyt the encrypted message in ios and with gnupg on linux too. So I will close this issue. If you are interested, I can create a gist, for the java code I used.

**Comment by krzyzanowskim** [comment]
I remember from the past that keys generated by the BouncyCastle were not strict with the protocol. It was about this flag, or about use correct key to sign/encrypt, don't remember details, though.

**Comment by asinoai** [comment]
Ok, thanks! I've updated the gist from the my comments with the working version of the java code.
