### ISSUE TITLE
Memory heavy code in PGP S2K

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#49]
1. In `[PGPS2K produceSessionKeyWithPassphrase:keySize:]`, iterated + salted keys are using a lot of memory, especially for iOS devices. For an uncoded count of 230, the coded count comes to 23,068,672 (**~22MB!**) - which is malloc'ed and realloc'ed, not good. 

2. Once you get outside the switch statement and call `[toHashData pgp_HashedWithAlgorithm:self.hashAlgorithm]`, most of the hash algorithms are calculating the hash in a single pass. This should be calculated iteratively when `toHashData` is being created so that the final malloc would now be `minBlockSize + offset` instead of `n * codedLength`.

**Comment by krzyzanowskim** [comment]
I had it like this in the early days  https://github.com/krzyzanowskim/ObjectivePGP/blob/0c2dd808cf9875ef3c5cc0728f5239aead0cf1e2/ObjectivePGP/PGPS2K.m#L116

then I moved to something else, that has been speed-optimized with the current approach. I see notes about memory from the very beginning.

**Comment by krzyzanowskim** [comment]
So far, doing an incremental calculation doesn't give many benefits. Memory footprint is comparable, but execution time is at best two times longer.
