### ISSUE TITLE
Change license to LGPLv3

### ISSUE THREAD

**Issue by dobegor** [krzyzanowskim/ObjectivePGP#50]
Could you please change the license to a more future-proof [LGPLv3](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3))?

It covers requirements in your LICENSE.txt.

**Comment by krzyzanowskim** [comment]
GPL is no-go.

**Comment by dobegor** [comment]
@krzyzanowskim 
LGPL is very different GPL, being much more permissive.
Perhaps [Apache 2](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) is more suitable for you?

My only point is to select a license that is kinda proofed to work. 

Thanks.

**Comment by krzyzanowskim** [comment]
Thanks for the concern. I don't have a strong enough reason to change the license.
