### ISSUE TITLE
Overriding preferred symmetric algorithm

### ISSUE THREAD

**Issue by jessearmand** [krzyzanowskim/ObjectivePGP#54]
Hello Marcin @krzyzanowskim, 

I am trying to override the preferred symmetric algorithm with `PGPSymmetricTripleDES`. 

I attached a diff that I did to achieve this:
[tripleDES.txt](https://github.com/krzyzanowskim/ObjectivePGP/files/889163/tripleDES.txt)

But, when I run the unit tests for plain text encryption / decryption. Specifically `testEncryption` on `ObjectivePGPTestSecurePlaintext.m` fails with empty data being decrypted.

Specifically, decryption process failed in the implementation of the following method of the library:

```objc
- (NSArray *) decryptWithSecretKeyPacket:(PGPSecretKeyPacket *)secretKeyPacket sessionKeyAlgorithm:(PGPSymmetricAlgorithm)sessionKeyAlgorithm sessionKeyData:(NSData *)sessionKeyData isIntegrityProtected:(BOOL *)isIntegrityProtected error:(NSError * __autoreleasing *)error
{

// ... Implementation omitted

    // check if suffix match
    if (![[prefixRandomFullData subdataWithRange:(NSRange){blockSize + 2 - 4, 2}] isEqualToData:[prefixRandomFullData subdataWithRange:(NSRange){blockSize + 2 - 2, 2}]]) {
        if (error) {
            *error = [NSError errorWithDomain:PGPErrorDomain code:0 userInfo:@{NSLocalizedDescriptionKey: @"Random suffix mismatch"}];
        }
        return nil;
    }

// ... Implementation omitted

}
```

Looking at the whole process of PGP encryption, decryption, all is working as expected with the same session key data used for encryption and decryption. The point of failure is when the data is decrypted with the secret key, due to random suffix mismatch.

I have tried to re-generate public / private key pairs with 4096 as a length. All with the same result, so I don't think that how the public / private key is generated becomes the underlying reason for this failure. This error is also referred to in issue #48.

Would you be able to explain what is the reason for this, and if there's any way that we can override the preferred symmetric algorithm? 

Thanks.

**Comment by krzyzanowskim** [comment]
The attached patch doesn't look right at first glance. I'll take a look at it in my spare time.

**Comment by jessearmand** [comment]
@krzyzanowskim Okay, but I didn't intend to make a pull request. As, I was just testing tripleDES symmetric algorithm to be used with the PGP.

Is it true that we can't change anything regarding the preferred symmetric algorithm? If this algorithm can be set by the user of the library, then what is the recommended way to do it?

**Comment by johnjacob22** [comment]
Any updates on this?

**Comment by krzyzanowskim** [comment]
Will be addressed before 1.0 release

**Comment by krzyzanowskim** [comment]
and I'm back here.
The preferred symmetric algorithm is calculated from the keys, isn't it? What is the reason to force different algorithm here, once again?

**Comment by krzyzanowskim** [comment]
@jessearmand if you'd prepare test case (in a form of PR is fine) I'm happy to investigate what is the issue.

**Comment by jessearmand** [comment]
@krzyzanowskim The issue with forcing symmetric algorithm seem to be fixed with the latest master branch.

I can't tell you any good reason to force it other than to be able to ensure that the encrypted message can be decrypted on the other end with an algorithm that I'm aware that the other end is using for decryption.

From the [RFC](https://tools.ietf.org/html/rfc4880#section-13.2):

> If an implementation can decrypt a message that a keyholder doesn't
   have in their preferences, the implementation SHOULD decrypt the
   message anyway, but MUST warn the keyholder that the protocol has
   been violated.  For example, suppose that Alice, above, has software
   that implements all algorithms in this specification.  Nonetheless,
   she prefers subsets for work or home.  If she is sent a message
   encrypted with IDEA, which is not in her preferences, the software
   warns her that someone sent her an IDEA-encrypted message, but it
   would ideally decrypt it anyway.

If the other endpoint can always decrypt the data with the keyholder preferences that is fine. But, I'm wondering if it's okay to violate the protocol a little bit by using a certain algorithm and ignoring the preferred ones on the key. Because, in my case it's not an email application, it's being used to encrypt data via REST API requests.

**Comment by krzyzanowskim** [comment]
I'm bit lazy here. Can you create a valid use case I could work on?

**Comment by jessearmand** [comment]
I will just close this issue. As I just explained above I didn’t see the errors with TripleDES anymore.
