### ISSUE TITLE
Put CryptoBox directory in ObjectivePGP.podspec

### ISSUE THREAD

**Issue by mssun** [krzyzanowskim/ObjectivePGP#56]
I guess you forgot to put `CryptoBox` in the ObjectivePGP.podspec.

```
  s.source_files = 'ObjectivePGP/*.{h,m}'
```

https://github.com/krzyzanowskim/ObjectivePGP/blob/master/ObjectivePGP.podspec#L20

**Comment by krzyzanowskim** [comment]
Should be fixed on `develop` branch. Please confirm and close the issue.

**Comment by mssun** [comment]
Yes, thanks.
