### ISSUE TITLE
ObjectivePGP object initialization error

### ISSUE THREAD

**Issue by john7770** [krzyzanowskim/ObjectivePGP#58]
I'm having trouble with initializing an ObjectivePGP object like it says in the usage section of the Read me. When I try to build the app I get 2 errors: 
: "_OBJC_CLASS_$_ObjectivePGP", referenced from: 

and 

: Linker command failed with exit code 1 (use -v to see invocation)
<img width="257" alt="screen shot 2017-05-29 at 6 39 13 pm cdt" src="https://cloud.githubusercontent.com/assets/19157445/26563836/29b7888e-449e-11e7-8cf1-ba063db09534.png">

I cannot initialize an object in either Objective-C nor Swift, the error only happens when I try to initialize the object but not creating it.

here is the affected code in Objective-C:

`ObjectivePGP *pgp = [[ObjectivePGP alloc] init];`
and in swift:
`let key: ObjectivePGP = ObjectivePGP();`

**Comment by krzyzanowskim** [comment]
Looks like you're not linking the target properly. Look at the new installation instructions for version 0.6.
