### ISSUE TITLE
Import does not work with two keys in file

### ISSUE THREAD

**Issue by m-merrell** [krzyzanowskim/ObjectivePGP#59]
I am using the following snippet to import keys from a file. In the test case, there were two keys in one file in the armoured format - public at the top and private at the end.

`[pgp importKeysFromFile:url.path allowDuplicates:NO];`

Only the public key gets imported no matter what. However, when I assigned private key to another variable, both keys imported successfully.

`NSString *private_key =@"";
...
[pgp importKeysFromFile:url.path allowDuplicates:NO];
[pgp importKeysFromData:[private_key dataUsingEncoding:NSUTF8StringEncoding] allowDuplicates:NO];`

Any help would be appreciated!

The keys are attached.
[96E3EABD7D02CA94.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/1048187/96E3EABD7D02CA94.asc.zip)

P.S. Importing public and private keys in binary format using that method works fine.

**Comment by krzyzanowskim** [comment]
Can you please verify if this is addressed in version 0.6 ?

**Comment by alpreu** [comment]
Issue persists, I cannot read the private key from my keyring:

`let keys = pgp.importKeys(fromFile: pgpKeyringPath)
for k in keys {
    print(k)
}`

prints 
<PGPKey: 0x6000002651c5>, publicKey: [KeyRedacted], secretKey: (null)

**Comment by krzyzanowskim** [comment]
It seems to work right with current codebase (>= 0.8). I'm closing it for now. I'm adding test case with the file you attached to test it.
