### ISSUE TITLE
Error decrypting large files

### ISSUE THREAD

**Issue by jmjordan** [krzyzanowskim/ObjectivePGP#6]
I receive the following exception when attempting to decrypt larger files. In this case the file is 2KB and the secret key is 4096 bits. I have successfully decrypted smaller files with the same code.

(
	0   CoreFoundation                      0x0000000111192f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110e2bbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000111192e6d +[NSException raise:format:] + 205
	3   Foundation                          0x000000010ec9fac7 -[NSData(NSData) subdataWithRange:] + 252
	4   PlainText                           0x000000010ca1799d +[PGPPacketFactory packetWithData:offset:] + 305
	5   PlainText                           0x000000010ca10b00 -[ObjectivePGP readPacketsFromData:] + 127
	6   PlainText                           0x000000010ca0df3d -[ObjectivePGP decryptData:passphrase:error:] + 161
	7   PlainText                           0x000000010c91b6a7 -[<omitted>] + 951
	8   UIKit                               0x000000010fb3ef50 __40-[UIDocument openWithCompletionHandler:]_block_invoke380 + 61
	9   Foundation                          0x000000010ecd1727 -[NSFileCoordinator _invokeAccessor:thenCompletionHandler:] + 180
	10  Foundation                          0x000000010ecd1662 __73-[NSFileCoordinator coordinateReadingItemAtURL:options:error:byAccessor:]_block_invoke + 97
	11  Foundation                          0x000000010edb4cd7 __85-[NSFileCoordinator(NSPrivate) _coordinateReadingItemAtURL:options:error:byAccessor:]_block_invoke335 + 94
	12  Foundation                          0x000000010edb4a26 -[NSFileCoordinator(NSPrivate) _invokeAccessor:orDont:andRelinquishAccessClaim:] + 300
	13  Foundation                          0x000000010ecd0011 -[NSFileCoordinator(NSPrivate) _coordinateReadingItemAtURL:options:error:byAccessor:] + 634
	14  Foundation                          0x000000010eccfd8b -[NSFileCoordinator coordinateReadingItemAtURL:options:error:byAccessor:] + 80
	15  UIKit                               0x000000010fb3eaba __40-[UIDocument openWithCompletionHandler:]_block_invoke + 328
	16  libdispatch.dylib                   0x0000000112154ba6 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00000001121727f4 _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x000000011215ab22 _dispatch_queue_drain + 1417
	19  libdispatch.dylib                   0x000000011215a432 _dispatch_queue_invoke + 235
	20  libdispatch.dylib                   0x000000011215cfc1 _dispatch_root_queue_drain + 685
	21  libdispatch.dylib                   0x000000011215e5d9 _dispatch_worker_thread3 + 111
	22  libsystem_pthread.dylib             0x00000001124f6637 _pthread_wqthread + 729
	23  libsystem_pthread.dylib             0x00000001124f440d start_wqthread + 13
)

**Comment by krzyzanowskim** [comment]
show me the file so I can look at the structure to guess what cause it might be

**Comment by krzyzanowskim** [comment]
Please verify if this is still an issue after fix https://github.com/krzyzanowskim/ObjectivePGP/pull/31

**Comment by jmjordan** [comment]
I would like to, but I am having trouble using the project with Cocoapods now that I have use_frameworks! enabled. The problem seems to come from having to add the OpenSSL-Universal pod manually.

**Comment by krzyzanowskim** [comment]
That's the Cocoapods limitation, yes.
I simply added ObjectivePGP and OpenSSL manually to my the project, that seems the only option for `use_frameworks!` in cocoapods.

**Comment by jmjordan** [comment]
Thanks! I'm almost back up and running. I'm now getting this error:

`duplicate symbol _OBJC_CLASS_$_PGPSecretSubKeyPacket in:
    /Users/jonathan/Library/Developer/Xcode/DerivedData/DropboxPlayground-chaksuosmdzkkcfcbuwjmiswgrra/Build/Intermediates/DropboxPlayground.build/Debug-iphonesimulator/DropboxPlayground.build/Objects-normal/x86_64/PGPKey.o
    /Users/jonathan/Library/Developer/Xcode/DerivedData/DropboxPlayground-chaksuosmdzkkcfcbuwjmiswgrra/Build/Intermediates/DropboxPlayground.build/Debug-iphonesimulator/DropboxPlayground.build/Objects-normal/x86_64/PGPSecretSubKeyPacket.o
duplicate symbol _OBJC_METACLASS_$_PGPSecretSubKeyPacket in:
    /Users/jonathan/Library/Developer/Xcode/DerivedData/DropboxPlayground-chaksuosmdzkkcfcbuwjmiswgrra/Build/Intermediates/DropboxPlayground.build/Debug-iphonesimulator/DropboxPlayground.build/Objects-normal/x86_64/PGPKey.o
    /Users/jonathan/Library/Developer/Xcode/DerivedData/DropboxPlayground-chaksuosmdzkkcfcbuwjmiswgrra/Build/Intermediates/DropboxPlayground.build/Debug-iphonesimulator/DropboxPlayground.build/Objects-normal/x86_64/PGPSecretSubKeyPacket.o`

Are you adding OPGP as a static library or as source code?

**Comment by jmjordan** [comment]
Nevermind. I found the problem. PGPKey.m was importing PGPSecretSubKeyPacket.m instead of PGPSecretSubKeyPacket.h.

**Comment by jmjordan** [comment]
It's been a while since I originally found the problem, but I am no longer able to reproduce the error.

**Comment by krzyzanowskim** [comment]
thank you! 👍
