### ISSUE TITLE
CocoaPods issue

### ISSUE THREAD

**Issue by amolpokale** [krzyzanowskim/ObjectivePGP#60]
Hello Sir,
I am currently use cocoa pods in my project which having some dynamic framework so i have to mention use_framework in my pod file. objectivePGP is static framework, so if i tried to install the pods it showing me issue **" transitive dependencies that include static binaries"**.

**Comment by krzyzanowskim** [comment]
This is as expected. ObjectivePGP is a static library due to OpenSSL dependency. Can't be overcome as of today.

**Comment by johnjacob22** [comment]
@krzyzanowskim I noticed that the installation instructions for Cocoapods now includes `use_frameworks!`. Did something change to enable ObjectivePGP to be built alongside other dynamic frameworks?

**Comment by krzyzanowskim** [comment]
yes, it's built  as a dynamic framework now
