### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by a4arpan** [krzyzanowskim/ObjectivePGP#61]
Can you also provide a swift version

**Comment by krzyzanowskim** [comment]
you should be able to use the library with Swift. More Swift compatibility will come with the next version though

**Comment by krzyzanowskim** [comment]
You can use ObjectivePGP with Swift very easily. Especially since the 0.6.1 release.

https://github.com/krzyzanowskim/ObjectivePGP/blob/master/ObjectivePGP.playground/Contents.swift
