### ISSUE TITLE
Creating keys with ObjectivePGP

### ISSUE THREAD

**Issue by racerxdl** [krzyzanowskim/ObjectivePGP#63]
I checked the source code but I couldn't find any call to create a public/private key pair using this library. Is there a way to do it?

Thanks

**Comment by krzyzanowskim** [comment]
Not at the moment. This function should be available in 1-2 months or earlier.

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/ObjectivePGP#generate-new-key
