### ISSUE TITLE
Uncaught exception for signing without passphrase

### ISSUE THREAD

**Issue by tobiasjungnickel** [krzyzanowskim/ObjectivePGP#67]
when signing data with a key that has no passphrase (passphrase: nil or "") an uncaught exception is raised.

`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Encryption failed'`

**Comment by krzyzanowskim** [comment]
can you share sample key for test? is it that the key has no passphrase or the passphrase is not provided?

**Comment by tobiasjungnickel** [comment]
i created the attached key with GPG Keychain from [GPG Suite](https://gpgtools.org) on the Mac and just didn't provide a passphrase in the textfield
[0D8BA9FB.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/1222323/0D8BA9FB.asc.zip)

**Comment by krzyzanowskim** [comment]
Can't reproduce, what is your code for that key?

**Comment by tobiasjungnickel** [comment]
here is my code in Swift
```
let pgp = ObjectivePGP()
//"mykeyfile.asc": method returning my keyfile
pgp.importKeys(fromFile: "mykeyfile.asc")
//"shortKeyString": short string of my key
let key = pgp.findKey(forIdentifier: "shortKeyString")
//<PGPKey: 0x61000002b9e0>, publicKey: 137A55C6DEE347C3, secretKey: 137A55C6DEE347C3
do {
    try pgp.sign(Data(), using: key!, passphrase: nil, detached: true)
} catch let error as NSError {
    print(error.debugDescription)
}
```

**Comment by krzyzanowskim** [comment]
Hm.... Are you able to create sample project? What version you're at?

**Comment by krzyzanowskim** [comment]
@tobiasjungnickel can you give a try to the version 0.7 and let me know if that change anything? thanks.

**Comment by tobiasjungnickel** [comment]
@krzyzanowskim yes, it's working now. Thanks!
