### ISSUE TITLE
Demo Swift project or instructions

### ISSUE THREAD

**Issue by bitbybitllc** [krzyzanowskim/ObjectivePGP#68]
I'm trying to use this library in a swift project for mobile devices and having no luck. I was able to solve the transitive dependencies issue when using cocoa pods but now when compiling in Xcode I get 36+ Apple Mach-O Linker Errors related to the ObjectivePGP library.

Any chance you could make a demo project for swift and upload it for others to use as a starting point for future projects kind of like Parse did in the past?

**Comment by krzyzanowskim** [comment]
When you open the workspace, there is Swift playground available. It's enough to build the library and use the Playground.

What transitive dependencies you're talking about? Did you try manual integration as outlined in the README too?

**Comment by bitbybitllc** [comment]
I did try the manual integration which worked fine. But I played around with the cocoa pods installation method hoping that would solve my Mach-O linker errors.  When first installing via cocoa pods there was an error: 


"The 'Pods-PGPApp' target has transitive dependencies that include static binaries: (/Users/.../Pods/OpenSSL-Universal/lib-ios/libcrypto.a and /Users/.../Pods/OpenSSL-Universal/lib-ios/libssl.a)"

My solution was to add this to my pod file
"
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
"

**Comment by bitbybitllc** [comment]
I have the workspace file open in Xcode. How do I view the swift playground? Sorry I've never used playgrounds before.

**Comment by krzyzanowskim** [comment]
![screen shot 2017-08-17 at 00 32 31](https://user-images.githubusercontent.com/758033/29388107-9e2d8f6e-82e3-11e7-884d-7b0baea5e5fb.png)

**Comment by bitbybitllc** [comment]
I built the target fine but the playground still has "No such module 'ObjectivePGP'" error.

**Comment by bitbybitllc** [comment]
When using that play button I still get a similar error.

"Playground execution failed: error: ObjectivePGP.playground:2:8: error: no such module 'ObjectivePGP'
import ObjectivePGP
"

**Comment by krzyzanowskim** [comment]
Regarding transitive dependencies: It doesn't look like you're using the current version. There is no  OpenSSL dependency in the podspec.

Make sure you're building Mac target for the Playground. 
![screen shot 2017-08-17 at 08 48 43](https://user-images.githubusercontent.com/758033/29399306-f67fed3e-8328-11e7-927f-583e727ce4a9.png)
