### ISSUE TITLE
Accessing UserID Details from PGPKey object

### ISSUE THREAD

**Issue by dtchanpura** [krzyzanowskim/ObjectivePGP#69]
Is there a way I can access UserID information like "Test Key <testkey@testingdomain.com>" from the PGPKey object in Swift? if it is how can it be achieved?

Following is the code I am executing.

```swift
let testKey:String = "some base64 encoded string"
pgp.importKeys(from: Data(base64Encoded: testKey)!)
```

The key is stored and is available for encryption if needed but I need to access the User ID field from it.

I am able to access the packets in it as follows and able to see they are for public key (tag 6) and sub key packet (tag 14).

```swift
key.publicKey?.allKeyPackets()
```

**Comment by krzyzanowskim** [comment]
`key.publicKey?.users[0].userID` is probably what you're looking for

**Comment by dtchanpura** [comment]
Thanks. I got it. I was using 0.6.2, just upgraded to version 0.7

**Comment by krzyzanowskim** [comment]
Nice, what project you're on?

**Comment by dtchanpura** [comment]
I am learning creating iOS apps and as an example trying to make something like [OpenKeyChain](https://openkeychain.org/) (available for Android) for iOS.
