### ISSUE TITLE
[0.8] Silent exception in parseNewFormatHeaderPacket:

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#72]
In ```PGPPacket.m```:
```const UInt8 *lengthOctets = [headerData subdataWithRange:(NSRange){1, MIN((NSUInteger)5, headerData.length)}].bytes;``` needs to be changed to:

```const UInt8 *lengthOctets = [headerData subdataWithRange:(NSRange){1, MIN((NSUInteger)5, headerData.length - 1)}].bytes;```

Otherwise, smaller headers are failing with silent exceptions.

**Comment by krzyzanowskim** [comment]
nice catch, thanks. the NSData exception shouldn't that silent though hm.
