### ISSUE TITLE
How can I get the fingerprint of a key

### ISSUE THREAD

**Issue by danielfeelfine** [krzyzanowskim/ObjectivePGP#74]
Is there a method to get the fingerprint of a key generated with ObjectivePGP?

**Comment by krzyzanowskim** [comment]
Fingerprint is a property of `PGPKeyID`
`generatedKey.keyID.fingerprint.data`

**Comment by danielfeelfine** [comment]
The *fingerprint* is not found: 
![screen shot 2017-10-03 at 10 42 51](https://user-images.githubusercontent.com/1668289/31128230-89fafafe-a827-11e7-86f9-9ca2f49eb4eb.png)

**Comment by danielfeelfine** [comment]
This works:
```ObjectiveC
NSLog(@"Fingerprint %@", key.secretKey.fingerprint);
```
![screen shot 2017-10-03 at 10 57 27](https://user-images.githubusercontent.com/1668289/31128949-920e7ade-a829-11e7-8dd9-489ecf828281.png)

**Comment by krzyzanowskim** [comment]
there you go! :)

**Comment by danielfeelfine** [comment]
I use to identify and relate the key with other objects.

**Comment by krzyzanowskim** [comment]
I see... and for that purpose `keyID` should be sufficient. fingerprint derive from keyID data.
