### ISSUE TITLE
Not able to generate keys 

### ISSUE THREAD

**Issue by PmAbi1993** [krzyzanowskim/ObjectivePGP#75]
Hello Sir,

I am trying to generate some keys using the below code

PGPKeyGenerator *generator = [[PGPKeyGenerator alloc] init];
PGPKey *key = [generator generateFor:@"Marcin <marcin@example.com>" passphrase:nil];
NSData *publicKeyData = [key export:PGPPartialKeyPublic error:nil];
NSData *secretKeyData = [key export:PGPPartialKeySecret error:nil];

But I am unable to generate as they compiler says PGPKeyGenerator is not found..

**Comment by PmAbi1993** [comment]
I am trying this on a swift project and imported the project using cocoapods

**Comment by krzyzanowskim** [comment]
What version do you have? It's available since 0.8.0
