### ISSUE TITLE
Inbound Encryption issues for Posteo

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#76]
In `PGPPacket.m:194`:
```
NSAssert(bodyLength > 0, @"The packet is of indeterminate length");
```
Is failing for emails that posteo auto-encrypts. It fails on a packet towards the end of the encrypted data. If I disable the assert, the decryption works. 

Here's the PGP message:
[encrypted.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/1359098/encrypted.asc.zip)

You won't need the key since it asserts on ```readPacketsFromData```. You can basically call that without the key and cause the assert. 

If you do need the test keys, send us an email and I'll send them across.

**Comment by dsanghan** [comment]
Hmm, I don't see where in the spec it mentions that a `bodyLength` of `0` is invalid:
```
4.2.2.  New Format Packet Lengths

   New format packets have four possible ways of encoding length:

   1. A one-octet Body Length header encodes packet lengths of up to 191
      octets.

   2. A two-octet Body Length header encodes packet lengths of 192 to
      8383 octets.

   3. A five-octet Body Length header encodes packet lengths of up to
      4,294,967,295 (0xFFFFFFFF) octets in length.  (This actually
      encodes a four-octet scalar number.)

   4. When the length of the packet body is not known in advance by the
      issuer, Partial Body Length headers encode a packet of
      indeterminate length, effectively making it a stream.

4.2.2.1.  One-Octet Lengths

   A one-octet Body Length header encodes a length of 0 to 191 octets.
   This type of length header is recognized because the one octet value
   is less than 192.  The body length is equal to:

       bodyLen = 1st_octet;
```

**Comment by krzyzanowskim** [comment]
It's a possibly a implementation limitation of indeterminated length support. @dsanghan send me over the keys, I'll work on that.

**Comment by dsanghan** [comment]
Thanks for the super quick turnaround!
