### ISSUE TITLE
Missing literal data, Adding minimal set of subpackets

### ISSUE THREAD

**Issue by AlexEKoren** [krzyzanowskim/ObjectivePGP#79]
I'm sure you're getting tired of all the issues I'm posting, but this one is more of a question:

I'm receiving a lot of output in the debugger writing:

> [PGPSignaturePacket signData:withKey:subKey:passphrase:userID:error:]/438 Signature without subpackets. Define subpackets! Adding minimal set of subpackets.

and

> [ObjectivePGP encrypt:usingKeys:signWithKey:passphrase:armored:error:]/451 Missing literal data

Any ideas how I can silence these or fix the underlying issue?

**Comment by AlexEKoren** [comment]
Also, generating keys (when these logs are output) seems to create a significant lag on the main thread. On the order of seconds using an iPhone 5s.

**Comment by krzyzanowskim** [comment]
This should be a debug message as it's ok to create a signature with a minimal set of subpackets in some use cases. The logging, if extensive may affect the main thread.

**Comment by krzyzanowskim** [comment]
> [ObjectivePGP encrypt:usingKeys:signWithKey:passphrase:armored:error:]/451 Missing literal data

@AlexEKoren this one is an error report. Something went wrong. Is this a framework issue?

**Comment by krzyzanowskim** [comment]
I believe both are adressed in code
