### ISSUE TITLE
unable to sign with subkey made with GnuPG 2.1.18

### ISSUE THREAD

**Issue by palmin** [krzyzanowskim/ObjectivePGP#80]
I have problems using a secret subkey generated with GnuPG 2.1.18 to sign data.

Signing fails with a "Missing session key" error and I am not sure what I can do about this and not sure if the error is with the subkey or with how it is imported.

Not sure if useful, but I made a fork with a new unit test that provokes the problem:
   https://github.com/palmin/ObjectivePGP/commit/52d1453e0b8

Any suggestions on how I can better diagnose this problem?

**Comment by krzyzanowskim** [comment]
interesting, I'll try to reproduce. Is the key passphrase correct?

**Comment by palmin** [comment]
Yes. The super secure passphrase is correct. 😬

**Comment by daniel-legler** [comment]
FWIW I get the same error with keys generated using an earlier version of ObjectivePGP (when UNNetPGP was around)

**Comment by krzyzanowskim** [comment]
Ok, the issue is "GnuPG gnu-dummy (s2k 1001)" extension support. Let me think about it.....

**Comment by krzyzanowskim** [comment]
I've made a change on develop branch that addresses the issue. Please verify.

**Comment by palmin** [comment]
I can confirm that things are working for me.

The unit test I made that imports and subkey and signs with it now runs without error. 

The signatures made with the new changes verify in GitHub commits.
