### ISSUE TITLE
Decrypting with public key loaded only

### ISSUE THREAD

**Issue by yaderbh** [krzyzanowskim/ObjectivePGP#81]
Is it possible to decrypt an encrypted payload using only the public key?

```
let pbkeyd = try! key.export(PGPPartialKeyType.public, error: ())
let opgp = ObjectivePGP()
let pbkey = opgp.keys(from: pbkeyd).first

opgp.importKeys([pbkey])
let pt = opgp.decryptData(data, passphrase: nil)
```

pt variable results in nil. The data passed into decryptData was generated by calling encryptData and passing the PGPKey that contains the secret and public key.

**Comment by krzyzanowskim** [comment]
this is as expected. You need private key to decryot data encryoted with public key

**Comment by yaderbh** [comment]
The data was encrypted with the private key. I’m trying to decrypt the data with the public key WITHOUT the private key being loaded.

**Comment by krzyzanowskim** [comment]
shouldn't be. I'm not sure what do you mean that data was "encrypted" with the private key in the context of PGP. The private key is used to sign, not to encrypt.
