### ISSUE TITLE
Passphrase is not considered in Decrypting.

### ISSUE THREAD

**Issue by kristijanPetr** [krzyzanowskim/ObjectivePGP#89]
Even when I use passphrase while encrypting message 
![encryptmsg](https://user-images.githubusercontent.com/19203276/33230951-074973ac-d1ed-11e7-949d-34c18de75908.png)

Problem is when I try to decrypt the message I can provide some different string to Passphrase and the message is successfully decrypted. 
![decryptmsg](https://user-images.githubusercontent.com/19203276/33230962-35f3e4c6-d1ed-11e7-83a5-f24e587de591.png)

Also here is keyPair exchange
![keypair](https://user-images.githubusercontent.com/19203276/33230968-4034ddc8-d1ed-11e7-90f3-3b8c0cb39a98.png)

**Comment by krzyzanowskim** [comment]
What version?

**Comment by kristijanPetr** [comment]
Okay thank you , I was using 0.9.3 version though.
