### ISSUE TITLE
Can't add the latest pod to project

### ISSUE THREAD

**Issue by PmAbi1993** [krzyzanowskim/ObjectivePGP#90]
I just tried to update the pod and see the errors below
![screen shot 2017-11-30 at 5 32 04 pm](https://user-images.githubusercontent.com/26453155/33429878-7e3042b0-d5f4-11e7-9018-e165b1d27ef7.png)

And the import call is also shown having an error. This was working fine in previous versions. 
![screen shot 2017-11-30 at 5 33 20 pm](https://user-images.githubusercontent.com/26453155/33429958-b313f10c-d5f4-11e7-9990-5dbd8110ea43.png)

Please help

**Comment by krzyzanowskim** [comment]
It looks like Cocoapods setup issue. Can you attach the project?

**Comment by PmAbi1993** [comment]
https://github.com/PmAbi1993/pgpTest

I have uploaded it. Can you please check?

**Comment by krzyzanowskim** [comment]
All good here. Try reinstall Cocoapods for the project:

Install `gem install cocoapods-deintegrate`
Then
1. `pod deintegrate`
1. delete `Pods`,
1. delete `Podfile.lock`
1. delete `PgpTest.xcworkspace`
1. `pod install`

![screen shot 2017-12-02 at 12 50 48](https://user-images.githubusercontent.com/758033/33515149-7637d20a-d75f-11e7-81cf-66b07d9caee9.png)
