### ISSUE TITLE
EdDSA Support

### ISSUE THREAD

**Issue by dsanghan** [krzyzanowskim/ObjectivePGP#92]
Didn't know this existed, but one of our users is using a key that uses the EdDSA algo (key algo tag 22). Is this something that is easy to add?

Here's the key:
http://pgp.mit.edu/pks/lookup?op=get&search=0x66E8D0707E40D9F9

**Comment by krzyzanowskim** [comment]
It's something that is definitely planned to have support for.

**Comment by oliverFU** [comment]
Hey,

thanks for your lib and you are doing a great job. I can't say often enough thank you. A couple of days ProtonMail proposed to move to ed25519 by default [1].

I have a short question about ed25519 support. Do you plan to add ed25519 support? 
Do you have an estimation about the effort to support encryption and verification using Ed25519+Cv25519?

I think generation of such keys would be necessary but handling such keys of others would be great. What do you think?


Thanks and best
Oliver

[1] https://www.mhonarc.org/archive/html/ietf-openpgp/2019-01/msg00000.html

**Comment by dsanghan** [comment]
@krzyzanowskim This seems to be the spec: https://tools.ietf.org/html/rfc8032

**Comment by iavael** [comment]
That’s the standard for EdDSA itself, not for it’s integration with
OpenPGP. The last one is still in draft (
https://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-04), but it
doesn’t stop implementations like gnupg from adopting it.
