### ISSUE TITLE
Public Key is invalid input data  but key works in android bouncycastle

### ISSUE THREAD

**Issue by Sunilkumarr** [krzyzanowskim/ObjectivePGP#93]
My public key :

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mI0EWip/DQMEAIdrzkN28B/ioxlkNfQRPEeWbf7Z2nIqtcAhraZQKe1Ydk67MdGA/byNhLVyWfG4umXXgyt6QI7CI87r/dPtJYaLK3g6/VUUEpY8DSL67rk2IXYE+WLXZC51MLfSr10dJXUhFpfj0v6HhN5K5sEXXaVxI2UsoU1oBHabw5RP8XLBABEBAAG0B3JleXR1bTGIrgQTAwIAFQUCWip/DQIbAwQLCQgHBhUIAgkKCwANCRBFbc05YP2HbgIbDKcpA/4z3yoR61MwlUxI28aeH1sLaAZwauPio7ErMNqjkQbLOtHy/EF1P/xFUzxSYc+SLa4TFsCRuokb3A/KkGbtLY9pFU9QSSK+P8gDPAV3MYXYrJsfnmqX3UyBipLHo4CLDTf+LIgc12zIz9ebDOQh/Ep//vQHE8/fZLWIoBrfGhZw+biNBFoqfw0CBACHa85DdvAf4qMZZDX0ETxHlm3+2dpyKrXAIa2mUCntWHZOuzHRgP28jYS1clnxuLpl14MrekCOwiPO6/3T7SWGiyt4Ov1VFBKWPA0i+u65NiF2BPli12QudTC30q9dHSV1IRaX49L+h4TeSubBF12lcSNlLKFNaAR2m8OUT/FywQARAQABiK4EGAMCABUFAloqfw0CGwMECwkIBwYVCAIJCgsADQkQRW3NOWD9h24CGwwoRgP+IewUzj+cXb7Uj63vFlzlHhILM+1dJuh7GuKgRTWn2EXypdy9EXBJ33WAa5Xz6osSCM8lYVC96SWI1fEZwi9rMddeDbU/SNJz/tM3aRlk+4YfOT90YmKo1DAXdnMOCrB7hR+zY3Equmiwn9i7bEGCCyy9PJXrgeUsZL+SSJFeE2M=
-----END PGP PUBLIC KEY BLOCK-----
```

Code: 

      NSString *filepath = [[NSBundle mainBundle] pathForResource:@"publicKey" ofType:@"txt"];
      NSError *error;
      NSString *fileContents = [NSString stringWithContentsOfFile:filepath encoding:NSUTF8StringEncoding error:&error];
      NSData* publickKeyData = [fileContents
                              dataUsingEncoding:NSUTF8StringEncoding];

      NSString *armoredString =   [PGPArmor armored:publickKeyData as:PGPArmorTypePublicKey];
      NSData* data = [armoredString dataUsingEncoding:NSUTF8StringEncoding];
     NSArray<PGPKey *> *keys = [ObjectivePGP readKeysFromData:data]; //its returning zero elements
    
    if(keys && keys.count ){
        NSLog(@"Found elements");
    }else{
        NSLog(@"No elements in it");
    }

I have created a sample for this : [sample  link ](https://drive.google.com/open?id=1a7DzJZO1B7VDZBVUn1UYrDMRKyMHVd2e)

**Comment by krzyzanowskim** [comment]
This is not a public key you attached, it's a **secret** key, although the message headers say otherwise.

**Comment by krzyzanowskim** [comment]
The armored message doesn't have a checksum, hence "Missing checksum" and ObjectivePGP expect the checksum. I made it required, while actually, it's optional so I have to adjust that.

**Comment by Sunilkumarr** [comment]
@krzyzanowskim Sorry before it was private  key update the public key now

**Comment by krzyzanowskim** [comment]
It's fixed. Fix will be available with the next release.

**Comment by Sunilkumarr** [comment]
@krzyzanowskim Thanks,  i tried with the develop branch 
 by pointing to pod to develop 
       ```pod 'ObjectivePGP', :git => 'https://github.com/krzyzanowskim/ObjectivePGP.git', :branch => 'develop'```


Tried  with above public key
```
mI0EWip/DQMEAIdrzkN28B/ioxlkNfQRPEeWbf7Z2nIqtcAhraZQKe1Ydk67MdGA/byNhLVyWfG4umXXgyt6QI7CI87r/dPtJYaLK3g6/VUUEpY8DSL67rk2IXYE+WLXZC51MLfSr10dJXUhFpfj0v6HhN5K5sEXXaVxI2UsoU1oBHabw5RP8XLBABEBAAG0B3JleXR1bTGIrgQTAwIAFQUCWip/DQIbAwQLCQgHBhUIAgkKCwANCRBFbc05YP2HbgIbDKcpA/4z3yoR61MwlUxI28aeH1sLaAZwauPio7ErMNqjkQbLOtHy/EF1P/xFUzxSYc+SLa4TFsCRuokb3A/KkGbtLY9pFU9QSSK+P8gDPAV3MYXYrJsfnmqX3UyBipLHo4CLDTf+LIgc12zIz9ebDOQh/Ep//vQHE8/fZLWIoBrfGhZw+biNBFoqfw0CBACHa85DdvAf4qMZZDX0ETxHlm3+2dpyKrXAIa2mUCntWHZOuzHRgP28jYS1clnxuLpl14MrekCOwiPO6/3T7SWGiyt4Ov1VFBKWPA0i+u65NiF2BPli12QudTC30q9dHSV1IRaX49L+h4TeSubBF12lcSNlLKFNaAR2m8OUT/FywQARAQABiK4EGAMCABUFAloqfw0CGwMECwkIBwYVCAIJCgsADQkQRW3NOWD9h24CGwwoRgP+IewUzj+cXb7Uj63vFlzlHhILM+1dJuh7GuKgRTWn2EXypdy9EXBJ33WAa5Xz6osSCM8lYVC96SWI1fEZwi9rMddeDbU/SNJz/tM3aRlk+4YfOT90YmKo1DAXdnMOCrB7hR+zY3Equmiwn9i7bEGCCyy9PJXrgeUsZL+SSJFeE2M=
```

 but still i see the same issue what can be the problem ?

Thanks

**Comment by krzyzanowskim** [comment]
it won't work like this, CocoaPods uses precompiled framework. Best is use build-framework.sh and point to local repo

**Comment by Sunilkumarr** [comment]
@krzyzanowskim  I tried by adding  path of  build-framework.sh in ObjectivePGP develop branch repo  in Build Phases --> Run Script  and pointed to local repo in pods file

But is see that  this method is returns   zero elements keys 
  
```
NSArray<PGPKey *> *keys = [ObjectivePGP readKeysFromData:data]; //its returning zero elements

```

**Comment by krzyzanowskim** [comment]
no, you have to

1. clone
2. run `./build-framework.sh` that build the frameworks and update the `Frameworks` directory
3. point your `Podfile` `pod` to you local PATH https://guides.cocoapods.org/using/the-podfile.html#using-the-files-from-a-folder-local-to-the-machine
4. reinstall pods so it uses the new path

or wait for the release.

**Comment by Sunilkumarr** [comment]
@krzyzanowskim  Thanks for help , Tried with this approach also but i see readKeysFromData returns zero elements keys will wait for release
