### ISSUE TITLE
How I can change keyBitsLength to 4096?

### ISSUE THREAD

**Issue by danielfeelfine** [krzyzanowskim/ObjectivePGP#96]
I need to change the [_keyBitsLength](https://github.com/krzyzanowskim/ObjectivePGP/blob/master/ObjectivePGP/PGPKeyGenerator.m#L42) from *3072* to *4096*. Is it possible?

Thanks

**Comment by krzyzanowskim** [comment]
This is a readwrite property, just set it to the new value

**Comment by danielfeelfine** [comment]
How I set this on `init` method?

```
PGPKeyGenerator *generator = [[PGPKeyGenerator alloc] init];
```

**Comment by krzyzanowskim** [comment]
you dont. you set it on an instance

**Comment by danielfeelfine** [comment]
In `ObjectivePGP *pgp;`? How?

**Comment by krzyzanowskim** [comment]
The `PGPKeyGenerator` instance

**Comment by danielfeelfine** [comment]
<img width="1146" alt="screen shot 2018-01-20 at 12 51 50 am" src="https://user-images.githubusercontent.com/1668289/35179196-400f323e-fd7c-11e7-8345-05353dbcf12b.png">

What is wrong?

**Comment by danielfeelfine** [comment]
I solved with:
```
PGPKeyGenerator *generator = [[PGPKeyGenerator alloc] init];
[generator setKeyBitsLength:4096];
```
