### ISSUE TITLE
Error when encrypt and sign in one operation.

### ISSUE THREAD

**Issue by oliverFU** [krzyzanowskim/ObjectivePGP#97]
Hey,

when encrypting and signing in one call (encrypt(... addSignature: true ...)) and keys contains a public key the encryption failed because all keys are used for signing and one is no secret key.
Here is a playground example:
```swift
// Generate new key
let key1 = KeyGenerator().generate(for: "marcin@krzyzanowskim.com", passphrase: nil)
let key2 = KeyGenerator().generate(for: "fran@krzyzanowskim.com", passphrase: nil)
let plaintext = Data(bytes: [1,2,3,4,5])
// Encrypt 5 bytes using selected key
if let pkData = try? key2.export(keyType: .public), let pk = try? ObjectivePGP.readKeys(from: pkData) {
    var keys = pk keys.append(key1)
    _ = try ObjectivePGP.encrypt(plaintext, addSignature: false, using: keys)
    do { 
    _ = try ObjectivePGP.encrypt(plaintext, addSignature: true, using: keys) 
    } catch{ 
    print(error) 
    } 
}
```
I fixed it when calling the signing function in the encryption function one should only consider secret keys.

```objc
if (shouldSign) { // sign data 
    if requested let signKeys = [NSMutableArray<PGPKey *> array]; 
    for (PGPKey* key in keys) { 
        if (key.secretKey && key.signingSecretKey != NULL){ [signKeys addObject:key];
    } 
}

content = [self sign:dataToEncrypt detached:NO usingKeys:signKeys passphraseForKey:passphraseForKeyBlock error:error];
```

When decrypting a message and verification is true, the function returns the decrypted message when the signature is wrong, missing or missing public key. I am not sure how to handle such cases. 

Cheers
Oliver

**Comment by krzyzanowskim** [comment]
hm... this check is already in `-[ObjectivePGP sign:detached:usingKeys:passphraseForKey:]`. Debug should report `Can't sign data` and most likely error is set.

**Comment by krzyzanowskim** [comment]
@oliverFU does the https://github.com/krzyzanowskim/ObjectivePGP/commit/eb2208eb222448bc4c5e4613e60c9d98bd178023 address the issue for you (without the PR) ?

**Comment by oliverFU** [comment]
@krzyzanowskim  I don't think it solves the problem. Since in encrypt you call sign with all keys. Only the private key(s) in array ([keys]) should be considered. I mean my playground example is a typical use case.

I will revisit the PR and following your comments.

**Comment by krzyzanowskim** [comment]
The private keys are selected inside the sign method. Without proper key signature is not created and signature fails with an error.

**Comment by oliverFU** [comment]
Sure, but assume Alice like to send an encrypted and signed message to Bob.
Alice has her own secret key sk_A and Bob's public key pk_B.
When calling  ObjectivePGP.encrypt(plaintext, addSignature: true, using: keys), keys contains pk_B and sk_A because we like to encrypt and sign (addSignature: true).

Inside the encrypt method,  the sign method is called with the array keys and sign throws an error because keys contains Bob's public key pk_B.
But when calling encrypt and addSignature, our intention was to use only pk_B for encryption and sk_A for signing (and may for encryption). 

Therefore, encrypt method should distinguish between signing and encryption keys either inside (like in PR) or outside (like the inputs of encrypt in a previous version).

**Comment by krzyzanowskim** [comment]
> But when calling encrypt and addSignature, our intention was to use only pk_B for encryption and sk_A for signing (and may for encryption).

I see your point. It's not the intention of that call now. The intention is to encrypt and sign with the same keys. I don't like two parameters with keys as it overlaps for the most common case. Maybe some optional filter block, will think about it more
